### ISSUE TITLE
WebApp:Import-AzWebAppKeyVaultCertificate api version bug

### ISSUE THREAD

**Issue by lilpug** [Azure/azure-powershell#15091]
## Description

When running the Import-AzWebAppKeyVaultCertificate command using the latest CLI and using a full pathed version of the keyvault "as its in a different subscription level", it returns the following response. 

_"The api-version '2016-10-01' is invalid. The supported versions are
'2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-
01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-0
7-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016
-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-
02-26,2014-04'."_

While running the command using Debug mode, I can see that when its calling out to the keyvault API, its using the wrong API version to the one it used to get the list of keyvaults etc, the failing api version it uses is "2016-10-01" which is not in the accepted list for that API call. I suspect it might be a typo and should actually be "2016-09-01" which is what the prior API call uses before the one that is failing.

## Steps to reproduce

```powershell
$keyvaultPath = "/subscriptions/$($bindings.keyvault.subscriptionId)/resourceGroups/$($bindings.keyvault.resourceGroup)/providers/Microsoft.KeyVault/vaults/$($bindings.keyvault.name)"

Import-AzWebAppKeyVaultCertificate -ResourceGroupName $appBinding.resourceGroup -webAppName $appBinding.name -KeyVaultName  $keyvaultPath -CertName $certificateName -Debug
```

![image](https://user-images.githubusercontent.com/1824684/119335100-ce21ee80-bc83-11eb-830d-4af996468a11.png)
![image](https://user-images.githubusercontent.com/1824684/119335183-ee51ad80-bc83-11eb-9ffc-5c0f99751b18.png)

**Comment by Kotasudhakarreddy** [comment]
@lilpug. Will check on it.

**Comment by panchagnula** [comment]
@Kotasudhakarreddy this is an AKV API, they might have made some change on their end, is there any reason we are using a specific api-version on our end, instead of simply using the default ap-version?

**Comment by isra-fel** [comment]
Hi @Kotasudhakarreddy @panchagnula , I believe the root cause is not wrong AKV API version, 2016-06-01 has always been a valid and stable api version. However, if you look at the second screenshot, it's the URI that's wrong.
My theroy is that ARM routed this request to another RP which doesn't accept 2016-06-01 (because that RP is not AKV).

It seems the URI issue was resolved in #15281 , and that's enough, we just need to get rid of the part to update AKV SDK. Your thoughts?

**Comment by Kotasudhakarreddy** [comment]
Yes I agree on the the your understanding. But along with the issue I have also updated the AKV SDK. @panchagnula your thought please.

**Comment by Kotasudhakarreddy** [comment]
@isra-fel I have rolled back the AKV SDK changes and sent the updated PR for review.

**Comment by lilpug** [comment]
has this been fixed on version 2.26.1 of the CLI as i still get the same issue after upgrading?

**Comment by isra-fel** [comment]
Hi @lilpug , this issue was fixed by Az.Websites 2.8.0.
Please [update the azure powershell module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.2.1#update-the-azure-powershell-module) and try again.

BTW CLI is [another product](https://docs.microsoft.com/en-us/cli/azure/), you were using [Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/?view=azps-6.2.1).

**Comment by lilpug** [comment]
apologies, you are correct, the latest az module version fixes this as its now got 2.8.1 Az.Websites in it. Thanks very much for this 👍
