### ISSUE TITLE
Set-AzPolicySetDefinition returns InternalServerError when the initiative is too large

### ISSUE THREAD

**Issue by falmirayasmin** [Azure/azure-powershell#20238]
### Description

To reproduce the issue, please follow the following steps:

1. Create custom policy with below definition
````
{
  "mode": "Indexed",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "not": {
            "field": "[concat('tags[', parameters('tagName'), ']')]",
            "in": "[parameters('tagValue')]"
          }
        }
      ]
    },
    "then": {
      "effect": "[parameters('effect')]"
    }
  },
  "parameters": {
    "tagName": {
      "type": "String",
      "metadata": {
        "displayName": "Tag Name",
        "description": "Name of the tag"
      }
    },
    "tagValue": {
      "type": "Array",
      "metadata": {
        "displayName": "tagValue",
        "description": null
      },
      "defaultValue": [
        ""
      ]
    },
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "Enable or disable the execution of the policy"
      },
      "allowedValues": [
        "Deny",
        "Audit"
      ]
    }
  }
}
````

2. Create a new initiative with 15 diferent reference the above policy
![image](https://user-images.githubusercontent.com/63050872/203825491-4e7332cc-2710-4c60-aa5c-3725c6213441.png)

3. Add a very large number "allowed values" in Tag Value paramater. 
![image](https://user-images.githubusercontent.com/63050872/203825789-e518a66c-fcb0-4a6b-af7b-3a2ef39ff62b.png)

I use the following dummy value for my testing 
````
[
"10000",
"10001",
"10002",
"10003",
"10004",
"10005",
"10006",
"10007",
"10008",
"10009",
"10010",
"10011",
"10012",
"10013",
"10014",
"10015",
"10016",
"10017",
"10018",
"10019",
"10020",
"10021",
"10022",
"10023",
"10024",
"10025",
"10026",
"10027",
"10028",
"10029",
"10030",
"10031",
"10032",
"10033",
"10034",
"10035",
"10036",
"10037",
"10038",
"10039",
"10040",
"10041",
"10042",
"10043",
"10044",
"10045",
"10046",
"10047",
"10048",
"10049",
"10050",
"10051",
"10052",
"10053",
"10054",
"10055",
"10056",
"10057",
"10058",
"10059",
"10060",
"10061",
"10062",
"10063",
"10064",
"10065",
"10066",
"10067",
"10068",
"10069",
"10070",
"10071",
"10072",
"10073",
"10074",
"10075",
"10076",
"10077",
"10078",
"10079",
"10080",
"10081",
"10082",
"10083",
"10084",
"10085",
"10086",
"10087",
"10088",
"10089",
"10090",
"10091",
"10092",
"10093",
"10094",
"10095",
"10096",
"10097",
"10098",
"10099",
"10100",
"10101",
"10102",
"10103",
"10104",
"10105",
"10106",
"10107",
"10108",
"10109",
"10110",
"10111",
"10112",
"10113",
"10114",
"10115",
"10116",
"10117",
"10118",
"10119",
"10120",
"10121",
"10122",
"10123",
"10124",
"10125",
"10126",
"10127",
"10128",
"10129",
"10130",
"10131",
"10132",
"10133",
"10134",
"10135",
"10136",
"10137",
"10138",
"10139",
"10140",
"10141",
"10142",
"10143",
"10144",
"10145",
"10146",
"10147",
"10148",
"10149",
"10150",
"10151",
"10152",
"10153",
"10154",
"10155",
"10156",
"10157",
"10158",
"10159",
"10160",
"10161",
"10162",
"10163",
"10164",
"10165",
"10166",
"10167",
"10168",
"10169",
"10170",
"10171",
"10172",
"10173",
"10174",
"10175",
"10176",
"10177",
"10178",
"10179",
"10180",
"10181",
"10182",
"10183",
"10184",
"10185",
"10186",
"10187",
"10188",
"10189",
"10190",
"10191",
"10192",
"10193",
"10194",
"10195",
"10196",
"10197",
"10198",
"10199",
"10200",
"10201",
"10202",
"10203",
"10204",
"10205",
"10206",
"10207",
"10208",
"10209",
"10210",
"10211",
"10212",
"10213",
"10214",
"10215",
"10216",
"10217",
"10218",
"10219",
"10220",
"10221",
"10222",
"10223",
"10224",
"10225",
"10226",
"10227",
"10228",
"10229",
"10230",
"10231",
"10232",
"10233",
"10234",
"10235",
"10236",
"10237",
"10238",
"10239",
"10240",
"10241",
"10242",
"10243",
"10244",
"10245",
"10246",
"10247",
"10248",
"10249",
"10250",
"10251",
"10252",
"10253",
"10254",
"10255",
"10256",
"10257",
"10258",
"10259",
"10260",
"10261",
"10262",
"10263",
"10264",
"10265",
"10266",
"10267",
"10268",
"10269",
"10270",
"10271",
"10272",
"10273",
"10274",
"10275",
"10276",
"10277",
"10278",
"10279",
"10280",
"10281",
"10282",
"10283",
"10284",
"10285",
"10286",
"10287",
"10288",
"10289",
"10290",
"10291",
"10292",
"10293",
"10294",
"10295",
"10296",
"10297",
"10298",
"10299",
"10300",
"10301",
"10302",
"10303",
"10304",
"10305",
"10306",
"10307",
"10308",
"10309",
"10310",
"10311",
"10312",
"10313",
"10314",
"10315",
"10316",
"10317",
"10318",
"10319",
"10320",
"10321",
"10322",
"10323",
"10324",
"10325",
"10326",
"10327",
"10328",
"10329",
"10330",
"10331",
"10332",
"10333",
"10334",
"10335",
"10336",
"10337",
"10338",
"10339",
"10340",
"10341",
"10342",
"10343",
"10344",
"10345",
"10346",
"10347",
"10348",
"10349",
"10350",
"10351",
"10352",
"10353",
"10354",
"10355",
"10356",
"10357",
"10358",
"10359",
"10360",
"10361",
"10362",
"10363",
"10364",
"10365",
"10366",
"10367",
"10368",
"10369",
"10370",
"10371",
"10372",
"10373",
"10374",
"10375",
"10376",
"10377",
"10378",
"10379",
"10380",
"10381",
"10382",
"10383",
"10384",
"10385",
"10386",
"10387",
"10388",
"10389",
"10390",
"10391",
"10392",
"10393",
"10394",
"10395",
"10396",
"10397",
"10398",
"10399",
"10400",
"10401",
"10402",
"10403",
"10404",
"10405",
"10406",
"10407",
"10408",
"10409",
"10410",
"10411",
"10412",
"10413",
"10414",
"10415",
"10416",
"10417",
"10418",
"10419",
"10420",
"10421",
"10422",
"10423",
"10424",
"10425",
"10426",
"10427",
"10428",
"10429",
"10430",
"10431",
"10432",
"10433",
"10434",
"10435",
"10436",
"10437",
"10438",
"10439",
"10440",
"10441",
"10442",
"10443",
"10444",
"10445",
"10446",
"10447",
"10448",
"10449",
"10450",
"10451",
"10452",
"10453",
"10454",
"10455",
"10456",
"10457",
"10458",
"10459",
"10460",
"10461",
"10462",
"10463",
"10464",
"10465",
"10466",
"10467",
"10468",
"10469",
"10470",
"10471",
"10472",
"10473",
"10474",
"10475",
"10476",
"10477",
"10478",
"10479",
"10480",
"10481",
"10482",
"10483",
"10484",
"10485",
"10486",
"10487",
"10488",
"10489",
"10490",
"10491",
"10492",
"10493",
"10494",
"10495",
"10496",
"10497",
"10498",
"10499",
"10500",
"10501",
"10502",
"10503",
"10504",
"10505",
"10506",
"10507",
"10508",
"10509",
"10510",
"10511",
"10512",
"10513",
"10514",
"10515",
"10516",
"10517",
"10518",
"10519",
"10520",
"10521",
"10522",
"10523",
"10524",
"10525",
"10526",
"10527",
"10528",
"10529",
"10530",
"10531",
"10532",
"10533",
"10534",
"10535",
"10536",
"10537",
"10538",
"10539",
"10540",
"10541",
"10542",
"10543",
"10544",
"10545",
"10546",
"10547",
"10548",
"10549",
"10550",
"10551",
"10552",
"10553",
"10554",
"10555",
"10556",
"10557",
"10558",
"10559",
"10560",
"10561",
"10562",
"10563",
"10564",
"10565",
"10566",
"10567",
"10568",
"10569",
"10570",
"10571",
"10572",
"10573",
"10574",
"10575",
"10576",
"10577",
"10578",
"10579",
"10580",
"10581",
"10582",
"10583",
"10584",
"10585",
"10586",
"10587",
"10588",
"10589",
"10590",
"10591",
"10592",
"10593",
"10594",
"10595",
"10596",
"10597",
"10598",
"10599",
"10600",
"10601",
"10602",
"10603",
"10604",
"10605",
"10606",
"10607",
"10608",
"10609",
"10610",
"10611",
"10612",
"10613",
"10614",
"10615",
"10616",
"10617",
"10618",
"10619",
"10620",
"10621",
"10622",
"10623",
"10624",
"10625",
"10626",
"10627",
"10628",
"10629",
"10630",
"10631",
"10632",
"10633",
"10634",
"10635",
"10636",
"10637",
"10638",
"10639",
"10640",
"10641",
"10642",
"10643",
"10644",
"10645",
"10646",
"10647",
"10648",
"10649",
"10650",
"10651",
"10652",
"10653",
"10654",
"10655",
"10656",
"10657",
"10658",
"10659",
"10660",
"10661",
"10662",
"10663",
"10664",
"10665",
"10666",
"10667",
"10668",
"10669",
"10670",
"10671",
"10672",
"10673",
"10674",
"10675",
"10676",
"10677",
"10678",
"10679",
"10680",
"10681",
"10682",
"10683",
"10684",
"10685",
"10686",
"10687",
"10688",
"10689",
"10690",
"10691",
"10692",
"10693",
"10694",
"10695",
"10696",
"10697",
"10698",
"10699",
"10700",
"10701",
"10702",
"10703",
"10704",
"10705",
"10706",
"10707",
"10708",
"10709",
"10710",
"10711",
"10712",
"10713",
"10714",
"10715",
"10716",
"10717",
"10718",
"10719",
"10720",
"10721",
"10722",
"10723",
"10724",
"10725",
"10726",
"10727",
"10728",
"10729",
"10730",
"10731",
"10732",
"10733",
"10734",
"10735",
"10736",
"10737",
"10738",
"10739",
"10740",
"10741",
"10742",
"10743",
"10744",
"10745",
"10746",
"10747",
"10748",
"10749",
"10750",
"10751",
"10752",
"10753",
"10754",
"10755",
"10756",
"10757",
"10758",
"10759",
"10760",
"10761",
"10762",
"10763",
"10764",
"10765",
"10766",
"10767",
"10768",
"10769",
"10770",
"10771",
"10772",
"10773",
"10774",
"10775",
"10776",
"10777",
"10778",
"10779",
"10780",
"10781",
"10782",
"10783",
"10784",
"10785",
"10786",
"10787",
"10788",
"10789",
"10790",
"10791",
"10792",
"10793",
"10794",
"10795",
"10796",
"10797",
"10798",
"10799",
"10800",
"10801",
"10802",
"10803",
"10804",
"10805",
"10806",
"10807",
"10808",
"10809",
"10810",
"10811",
"10812",
"10813",
"10814",
"10815",
"10816",
"10817",
"10818",
"10819",
"10820",
"10821",
"10822",
"10823",
"10824",
"10825",
"10826",
"10827",
"10828",
"10829",
"10830",
"10831",
"10832",
"10833",
"10834",
"10835",
"10836",
"10837",
"10838",
"10839",
"10840",
"10841",
"10842",
"10843",
"10844",
"10845",
"10846",
"10847",
"10848",
"10849",
"10850",
"10851",
"10852",
"10853",
"10854",
"10855",
"10856",
"10857",
"10858",
"10859",
"10860",
"10861",
"10862",
"10863",
"10864",
"10865",
"10866",
"10867",
"10868",
"10869",
"10870",
"10871",
"10872",
"10873",
"10874",
"10875",
"10876",
"10877",
"10878",
"10879",
"10880",
"10881",
"10882",
"10883",
"10884",
"10885",
"10886",
"10887",
"10888",
"10889",
"10890",
"10891",
"10892",
"10893",
"10894",
"10895",
"10896",
"10897",
"10898",
"10899",
"10900",
"10901",
"10902",
"10903",
"10904",
"10905",
"10906",
"10907",
"10908",
"10909",
"10910",
"10911",
"10912",
"10913",
"10914",
"10915",
"10916",
"10917",
"10918",
"10919",
"10920",
"10921",
"10922",
"10923",
"10924",
"10925",
"10926",
"10927",
"10928",
"10929",
"10930",
"10931",
"10932",
"10933",
"10934",
"10935",
"10936",
"10937",
"10938",
"10939",
"10940",
"10941",
"10942",
"10943",
"10944",
"10945",
"10946",
"10947",
"10948",
"10949",
"10950",
"10951",
"10952",
"10953",
"10954",
"10955",
"10956",
"10957",
"10958",
"10959",
"10960",
"10961",
"10962",
"10963",
"10964",
"10965",
"10966",
"10967",
"10968",
"10969",
"10970",
"10971",
"10972",
"10973",
"10974",
"10975",
"10976",
"10977",
"10978",
"10979",
"10980",
"10981",
"10982",
"10983",
"10984",
"10985",
"10986",
"10987",
"10988",
"10989",
"10990",
"10991",
"10992",
"10993",
"10994",
"10995",
"10996",
"10997",
"10998",
"10999",
"11000",
"11001",
"11002",
"11003",
"11004",
"11005",
"11006",
"11007",
"11008",
"11009",
"11010",
"11011",
"11012",
"11013",
"11014",
"11015",
"11016",
"11017",
"11018",
"11019",
"11020",
"11021",
"11022",
"11023",
"11024",
"11025",
"11026",
"11027",
"11028",
"11029",
"11030",
"11031",
"11032",
"11033",
"11034",
"11035",
"11036",
"11037",
"11038",
"11039",
"11040",
"11041",
"11042",
"11043",
"11044",
"11045",
"11046",
"11047",
"11048",
"11049",
"11050",
"11051",
"11052",
"11053",
"11054",
"11055",
"11056",
"11057",
"11058",
"11059",
"11060",
"11061",
"11062",
"11063",
"11064",
"11065",
"11066",
"11067",
"11068",
"11069",
"11070",
"11071",
"11072",
"11073",
"11074",
"11075",
"11076",
"11077",
"11078",
"11079",
"11080",
"11081",
"11082",
"11083",
"11084",
"11085",
"11086",
"11087",
"11088",
"11089",
"11090",
"11091",
"11092",
"11093",
"11094",
"11095",
"11096",
"11097",
"11098",
"11099",
"11100",
"11101",
"11102",
"11103",
"11104",
"11105",
"11106",
"11107",
"11108",
"11109",
"11110",
"11111",
"11112",
"11113",
"11114",
"11115",
"11116",
"11117",
"11118",
"11119",
"11120",
"11121",
"11122",
"11123",
"11124",
"11125",
"11126",
"11127",
"11128",
"11129",
"11130",
"11131",
"11132",
"11133",
"11134",
"11135",
"11136",
"11137",
"11138",
"11139",
"11140",
"11141",
"11142",
"11143",
"11144",
"11145",
"11146",
"11147",
"11148",
"11149",
"11150",
"11151",
"11152",
"11153",
"11154",
"11155",
"11156",
"11157",
"11158",
"11159",
"11160",
"11161",
"11162",
"11163",
"11164",
"11165",
"11166",
"11167",
"11168",
"11169",
"11170",
"11171",
"11172",
"11173",
"11174",
"11175",
"11176",
"11177",
"11178",
"11179",
"11180",
"11181",
"11182",
"11183",
"11184",
"11185",
"11186",
"11187",
"11188",
"11189",
"11190",
"11191",
"11192",
"11193",
"11194",
"11195",
"11196",
"11197",
"11198",
"11199",
"11200",
"11201",
"11202",
"11203",
"11204",
"11205",
"11206",
"11207",
"11208",
"11209",
"11210",
"11211",
"11212",
"11213",
"11214",
"11215",
"11216",
"11217",
"11218",
"11219",
"11220",
"11221",
"11222",
"11223",
"11224",
"11225",
"11226",
"11227",
"11228",
"11229",
"11230",
"11231",
"11232",
"11233",
"11234",
"11235",
"11236",
"11237",
"11238",
"11239",
"11240",
"11241",
"11242",
"11243",
"11244",
"11245",
"11246",
"11247",
"11248",
"11249",
"11250",
"11251",
"11252",
"11253",
"11254",
"11255",
"11256",
"11257",
"11258",
"11259",
"11260",
"11261",
"11262",
"11263",
"11264",
"11265",
"11266",
"11267",
"11268",
"11269",
"11270",
"11271",
"11272",
"11273",
"11274",
"11275",
"11276",
"11277",
"11278",
"11279",
"11280",
"11281",
"11282",
"11283",
"11284",
"11285",
"11286",
"11287",
"11288",
"11289",
"11290",
"11291",
"11292",
"11293",
"11294",
"11295",
"11296",
"11297",
"11298",
"11299",
"11300",
"11301",
"11302",
"11303",
"11304",
"11305",
"11306",
"11307",
"11308",
"11309",
"11310",
"11311",
"11312",
"11313",
"11314",
"11315",
"11316",
"11317",
"11318",
"11319",
"11320",
"11321",
"11322",
"11323",
"11324",
"11325",
"11326",
"11327",
"11328",
"11329",
"11330",
"11331",
"11332",
"11333",
"11334",
"11335",
"11336",
"11337",
"11338",
"11339",
"11340",
"11341",
"11342",
"11343",
"11344",
"11345",
"11346",
"11347",
"11348",
"11349",
"11350",
"11351",
"11352",
"11353",
"11354",
"11355",
"11356",
"11357",
"11358",
"11359",
"11360",
"11361",
"11362",
"11363",
"11364",
"11365",
"11366",
"11367",
"11368",
"11369",
"11370",
"11371",
"11372",
"11373",
"11374",
"11375",
"11376",
"11377",
"11378",
"11379",
"11380",
"11381",
"11382",
"11383",
"11384",
"11385",
"11386",
"11387",
"11388",
"11389",
"11390",
"11391",
"11392",
"11393",
"11394",
"11395",
"11396",
"11397",
"11398",
"11399",
"11400",
"11401",
"11402",
"11403",
"11404",
"11405",
"11406",
"11407",
"11408",
"11409",
"11410",
"11411",
"11412",
"11413",
"11414",
"11415",
"11416",
"11417",
"11418",
"11419",
"11420",
"11421",
"11422",
"11423",
"11424",
"11425",
"11426",
"11427",
"11428",
"11429",
"11430",
"11431",
"11432",
"11433",
"11434",
"11435",
"11436",
"11437",
"11438",
"11439",
"11440",
"11441",
"11442",
"11443",
"11444",
"11445",
"11446",
"11447",
"11448",
"11449",
"11450",
"11451",
"11452",
"11453",
"11454",
"11455",
"11456",
"11457",
"11458",
"11459",
"11460",
"11461",
"11462",
"11463",
"11464",
"11465",
"11466",
"11467",
"11468",
"11469",
"11470",
"11471",
"11472",
"11473",
"11474",
"11475",
"11476",
"11477",
"11478",
"11479",
"11480",
"11481",
"11482",
"11483",
"11484",
"11485",
"11486",
"11487",
"11488",
"11489",
"11490",
"11491",
"11492",
"11493",
"11494",
"11495",
"11496",
"11497",
"11498",
"11499",
"11500",
"11501",
"11502",
"11503",
"11504",
"11505",
"11506",
"11507",
"11508",
"11509",
"11510",
"11511",
"11512",
"11513",
"11514",
"11515",
"11516",
"11517",
"11518",
"11519",
"11520",
"11521",
"11522",
"11523",
"11524",
"11525",
"11526",
"11527",
"11528",
"11529",
"11530",
"11531",
"11532",
"11533",
"11534",
"11535",
"11536",
"11537",
"11538",
"11539",
"11540",
"11541",
"11542",
"11543",
"11544",
"11545",
"11546",
"11547",
"11548",
"11549",
"11550",
"11551",
"11552",
"11553",
"11554",
"11555",
"11556",
"11557",
"11558",
"11559",
"11560",
"11561",
"11562",
"11563",
"11564",
"11565",
"11566",
"11567",
"11568",
"11569",
"11570",
"11571",
"11572",
"11573",
"11574",
"11575",
"11576",
"11577",
"11578",
"11579",
"11580",
"11581",
"11582",
"11583",
"11584",
"11585",
"11586",
"11587",
"11588",
"11589",
"11590",
"11591",
"11592",
"11593",
"11594",
"11595",
"11596",
"11597",
"11598",
"11599",
"11600",
"11601",
"11602",
"11603",
"11604",
"11605",
"11606",
"11607",
"11608",
"11609",
"11610",
"11611",
"11612",
"11613",
"11614",
"11615",
"11616",
"11617",
"11618",
"11619",
"11620",
"11621",
"11622",
"11623",
"11624",
"11625",
"11626",
"11627",
"11628",
"11629",
"11630",
"11631",
"11632",
"11633",
"11634",
"11635",
"11636",
"11637",
"11638",
"11639",
"11640",
"11641",
"11642",
"11643",
"11644",
"11645",
"11646",
"11647",
"11648",
"11649",
"11650",
"11651",
"11652",
"11653",
"11654",
"11655",
"11656",
"11657",
"11658",
"11659",
"11660",
"11661",
"11662",
"11663",
"11664",
"11665",
"11666",
"11667",
"11668",
"11669",
"11670",
"11671",
"11672",
"11673",
"11674",
"11675",
"11676",
"11677",
"11678",
"11679",
"11680",
"11681",
"11682",
"11683",
"11684",
"11685",
"11686",
"11687",
"11688",
"11689",
"11690",
"11691",
"11692",
"11693",
"11694",
"11695",
"11696",
"11697",
"11698",
"11699",
"11700",
"11701",
"11702",
"11703",
"11704",
"11705",
"11706",
"11707",
"11708",
"11709",
"11710",
"11711",
"11712",
"11713",
"11714",
"11715",
"11716",
"11717",
"11718",
"11719",
"11720",
"11721",
"11722",
"11723",
"11724",
"11725",
"11726",
"11727",
"11728",
"11729",
"11730",
"11731",
"11732",
"11733",
"11734",
"11735",
"11736",
"11737",
"11738",
"11739",
"11740",
"11741",
"11742",
"11743",
"11744",
"11745",
"11746",
"11747",
"11748",
"11749",
"11750",
"11751",
"11752",
"11753",
"11754",
"11755",
"11756",
"11757",
"11758",
"11759",
"11760",
"11761",
"11762",
"11763",
"11764",
"11765",
"11766",
"11767",
"11768",
"11769",
"11770",
"11771",
"11772",
"11773",
"11774",
"11775",
"11776",
"11777",
"11778",
"11779",
"11780",
"11781",
"11782",
"11783",
"11784",
"11785",
"11786",
"11787",
"11788",
"11789",
"11790",
"11791",
"11792",
"11793",
"11794",
"11795",
"11796",
"11797",
"11798",
"11799",
"11800",
"11801",
"11802",
"11803",
"11804",
"11805",
"11806",
"11807",
"11808",
"11809",
"11810",
"11811",
"11812",
"11813",
"11814",
"11815",
"11816",
"11817",
"11818",
"11819",
"11820",
"11821",
"11822",
"11823",
"11824",
"11825",
"11826",
"11827",
"11828",
"11829",
"11830",
"11831",
"11832",
"11833",
"11834",
"11835",
"11836",
"11837",
"11838",
"11839",
"11840",
"11841",
"11842",
"11843",
"11844",
"11845",
"11846",
"11847",
"11848",
"11849",
"11850",
"11851",
"11852",
"11853",
"11854",
"11855",
"11856",
"11857",
"11858",
"11859",
"11860",
"11861",
"11862",
"11863",
"11864",
"11865",
"11866",
"11867",
"11868",
"11869",
"11870",
"11871",
"11872",
"11873",
"11874",
"11875",
"11876",
"11877",
"11878",
"11879",
"11880",
"11881",
"11882",
"11883",
"11884",
"11885",
"11886",
"11887",
"11888",
"11889",
"11890",
"11891",
"11892",
"11893",
"11894",
"11895",
"11896",
"11897",
"11898",
"11899",
"11900",
"11901",
"11902",
"11903",
"11904",
"11905",
"11906",
"11907",
"11908",
"11909",
"11910",
"11911",
"11912",
"11913",
"11914",
"11915",
"11916",
"11917",
"11918",
"11919",
"11920",
"11921",
"11922",
"11923",
"11924",
"11925",
"11926",
"11927",
"11928",
"11929",
"11930",
"11931",
"11932",
"11933",
"11934",
"11935",
"11936",
"11937",
"11938",
"11939",
"11940",
"11941",
"11942",
"11943",
"11944",
"11945",
"11946",
"11947",
"11948",
"11949",
"11950",
"11951",
"11952",
"11953",
"11954",
"11955",
"11956",
"11957",
"11958",
"11959",
"11960",
"11961",
"11962",
"11963",
"11964",
"11965",
"11966",
"11967",
"11968",
"11969",
"11970",
"11971",
"11972",
"11973",
"11974",
"11975",
"11976",
"11977",
"11978",
"11979",
"11980",
"11981",
"11982",
"11983",
"11984",
"11985",
"11986",
"11987",
"11988",
"11989",
"11990",
"11991",
"11992",
"11993",
"11994",
"11995",
"11996",
"11997",
"11998",
"11999",
"12000",
"12001",
"12002",
"12003",
"12004",
"12005",
"12006",
"12007",
"12008",
"12009",
"12010",
"12011",
"12012",
"12013",
"12014",
"12015",
"12016",
"12017",
"12018",
"12019",
"12020",
"12021",
"12022",
"12023",
"12024",
"12025",
"12026",
"12027",
"12028",
"12029",
"12030",
"12031",
"12032",
"12033",
"12034",
"12035",
"12036",
"12037",
"12038",
"12039",
"12040",
"12041",
"12042",
"12043",
"12044",
"12045",
"12046",
"12047",
"12048",
"12049",
"12050",
"12051",
"12052",
"12053",
"12054",
"12055",
"12056",
"12057",
"12058",
"12059",
"12060",
"12061",
"12062",
"12063",
"12064",
"12065",
"12066",
"12067",
"12068",
"12069",
"12070",
"12071",
"12072",
"12073",
"12074",
"12075",
"12076",
"12077",
"12078",
"12079",
"12080",
"12081",
"12082",
"12083",
"12084",
"12085",
"12086",
"12087",
"12088",
"12089",
"12090",
"12091",
"12092",
"12093",
"12094",
"12095",
"12096",
"12097",
"12098",
"12099",
"12100",
"12101",
"12102",
"12103",
"12104",
"12105",
"12106",
"12107",
"12108",
"12109",
"12110",
"12111",
"12112",
"12113",
"12114",
"12115",
"12116",
"12117",
"12118",
"12119",
"12120",
"12121",
"12122",
"12123",
"12124",
"12125",
"12126",
"12127",
"12128",
"12129",
"12130",
"12131",
"12132",
"12133",
"12134",
"12135",
"12136",
"12137",
"12138",
"12139",
"12140",
"12141",
"12142",
"12143",
"12144",
"12145",
"12146",
"12147",
"12148",
"12149",
"12150",
"12151",
"12152",
"12153",
"12154",
"12155",
"12156",
"12157",
"12158",
"12159",
"12160",
"12161",
"12162",
"12163",
"12164",
"12165",
"12166",
"12167",
"12168",
"12169",
"12170",
"12171",
"12172",
"12173",
"12174",
"12175",
"12176",
"12177",
"12178",
"12179",
"12180",
"12181",
"12182",
"12183",
"12184",
"12185",
"12186",
"12187",
"12188",
"12189",
"12190",
"12191",
"12192",
"12193",
"12194",
"12195",
"12196",
"12197",
"12198",
"12199",
"12200",
"12201",
"12202",
"12203",
"12204",
"12205",
"12206",
"12207",
"12208",
"12209",
"12210",
"12211",
"12212",
"12213",
"12214",
"12215",
"12216",
"12217",
"12218",
"12219",
"12220",
"12221",
"12222",
"12223",
"12224",
"12225",
"12226",
"12227",
"12228",
"12229",
"12230",
"12231",
"12232",
"12233",
"12234",
"12235",
"12236",
"12237",
"12238",
"12239",
"12240",
"12241",
"12242",
"12243",
"12244",
"12245",
"12246",
"12247",
"12248",
"12249",
"12250",
"12251",
"12252",
"12253",
"12254",
"12255",
"12256",
"12257",
"12258",
"12259",
"12260",
"12261",
"12262",
"12263",
"12264",
"12265",
"12266",
"12267",
"12268",
"12269",
"12270",
"12271",
"12272",
"12273",
"12274",
"12275",
"12276",
"12277",
"12278",
"12279",
"12280",
"12281",
"12282",
"12283",
"12284",
"12285",
"12286",
"12287",
"12288",
"12289",
"12290",
"12291",
"12292",
"12293",
"12294",
"12295",
"12296",
"12297",
"12298",
"12299",
"12300",
"12301",
"12302",
"12303",
"12304",
"12305",
"12306",
"12307",
"12308",
"12309",
"12310",
"12311",
"12312",
"12313",
"12314",
"12315",
"12316",
"12317",
"12318",
"12319",
"12320",
"12321",
"12322",
"12323",
"12324",
"12325",
"12326",
"12327",
"12328",
"12329",
"12330",
"12331",
"12332",
"12333",
"12334",
"12335",
"12336",
"12337",
"12338",
"12339",
"12340",
"12341",
"12342",
"12343",
"12344",
"12345",
"12346",
"12347",
"12348",
"12349",
"12350",
"12351",
"12352",
"12353",
"12354",
"12355",
"12356",
"12357",
"12358",
"12359",
"12360",
"12361",
"12362",
"12363",
"12364",
"12365",
"12366",
"12367",
"12368",
"12369",
"12370",
"12371",
"12372",
"12373",
"12374",
"12375",
"12376",
"12377",
"12378",
"12379",
"12380",
"12381",
"12382",
"12383",
"12384",
"12385",
"12386",
"12387",
"12388",
"12389",
"12390",
"12391",
"12392",
"12393",
"12394",
"12395",
"12396",
"12397",
"12398",
"12399",
"12400",
"12401",
"12402",
"12403",
"12404",
"12405",
"12406",
"12407",
"12408",
"12409",
"12410",
"12411",
"12412",
"12413",
"12414",
"12415",
"12416",
"12417",
"12418",
"12419",
"12420",
"12421",
"12422",
"12423",
"12424",
"12425",
"12426",
"12427",
"12428",
"12429",
"12430",
"12431",
"12432",
"12433",
"12434",
"12435",
"12436",
"12437",
"12438",
"12439",
"12440",
"12441",
"12442",
"12443",
"12444",
"12445",
"12446",
"12447",
"12448",
"12449",
"12450",
"12451",
"12452",
"12453",
"12454",
"12455",
"12456",
"12457",
"12458",
"12459",
"12460",
"12461",
"12462",
"12463",
"12464",
"12465",
"12466",
"12467",
"12468",
"12469",
"12470",
"12471",
"12472",
"12473",
"12474",
"12475",
"12476",
"12477",
"12478",
"12479",
"12480",
"12481",
"12482",
"12483",
"12484",
"12485",
"12486",
"12487",
"12488",
"12489",
"12490",
"12491",
"12492",
"12493",
"12494",
"12495",
"12496",
"12497",
"12498",
"12499",
"12500",
"12501",
"12502",
"12503",
"12504",
"12505",
"12506",
"12507",
"12508",
"12509",
"12510",
"12511",
"12512",
"12513",
"12514",
"12515",
"12516",
"12517",
"12518",
"12519",
"12520",
"12521",
"12522",
"12523",
"12524",
"12525",
"12526",
"12527",
"12528",
"12529",
"12530",
"12531",
"12532",
"12533",
"12534",
"12535",
"12536",
"12537",
"12538",
"12539",
"12540",
"12541",
"12542",
"12543",
"12544",
"12545",
"12546",
"12547",
"12548",
"12549",
"12550",
"12551",
"12552",
"12553",
"12554",
"12555",
"12556",
"12557",
"12558",
"12559",
"12560",
"12561",
"12562",
"12563",
"12564",
"12565",
"12566",
"12567",
"12568",
"12569",
"12570",
"12571",
"12572",
"12573",
"12574",
"12575",
"12576",
"12577",
"12578",
"12579",
"12580",
"12581",
"12582",
"12583",
"12584",
"12585",
"12586",
"12587",
"12588",
"12589",
"12590",
"12591",
"12592",
"12593",
"12594",
"12595",
"12596",
"12597",
"12598",
"12599",
"12600",
"12601",
"12602",
"12603",
"12604",
"12605",
"12606",
"12607",
"12608",
"12609",
"12610",
"12611",
"12612",
"12613",
"12614",
"12615",
"12616",
"12617",
"12618",
"12619",
"12620",
"12621",
"12622",
"12623",
"12624",
"12625",
"12626",
"12627",
"12628",
"12629",
"12630",
"12631",
"12632",
"12633",
"12634",
"12635",
"12636",
"12637",
"12638",
"12639",
"12640",
"12641",
"12642",
"12643",
"12644",
"12645",
"12646",
"12647",
"12648",
"12649",
"12650",
"12651",
"12652",
"12653",
"12654",
"12655",
"12656",
"12657",
"12658",
"12659",
"12660",
"12661",
"12662",
"12663",
"12664",
"12665",
"12666",
"12667",
"12668",
"12669",
"12670",
"12671",
"12672",
"12673",
"12674",
"12675",
"12676",
"12677",
"12678",
"12679",
"12680",
"12681",
"12682",
"12683",
"12684",
"12685",
"12686",
"12687",
"12688",
"12689",
"12690",
"12691",
"12692",
"12693",
"12694",
"12695",
"12696",
"12697",
"12698",
"12699",
"12700",
"12701",
"12702",
"12703",
"12704",
"12705",
"12706",
"12707",
"12708",
"12709",
"12710",
"12711",
"12712",
"12713",
"12714",
"12715",
"12716",
"12717",
"12718",
"12719",
"12720",
"12721",
"12722",
"12723",
"12724",
"12725",
"12726",
"12727",
"12728",
"12729",
"12730",
"12731",
"12732",
"12733",
"12734",
"12735",
"12736",
"12737",
"12738",
"12739",
"12740",
"12741",
"12742",
"12743",
"12744",
"12745",
"12746",
"12747",
"12748",
"12749",
"12750",
"12751",
"12752",
"12753",
"12754",
"12755",
"12756",
"12757",
"12758",
"12759",
"12760",
"12761",
"12762",
"12763",
"12764",
"12765",
"12766",
"12767",
"12768",
"12769",
"12770",
"12771",
"12772",
"12773",
"12774",
"12775",
"12776",
"12777",
"12778",
"12779",
"12780",
"12781",
"12782",
"12783",
"12784",
"12785",
"12786",
"12787",
"12788",
"12789",
"12790",
"12791",
"12792",
"12793",
"12794",
"12795",
"12796",
"12797",
"12798",
"12799",
"12800",
"12801",
"12802",
"12803",
"12804",
"12805",
"12806",
"12807",
"12808",
"12809",
"12810",
"12811",
"12812",
"12813",
"12814",
"12815",
"12816",
"12817",
"12818",
"12819",
"12820",
"12821",
"12822",
"12823",
"12824",
"12825",
"12826",
"12827",
"12828",
"12829",
"12830",
"12831",
"12832",
"12833",
"12834",
"12835",
"12836",
"12837",
"12838",
"12839",
"12840",
"12841",
"12842",
"12843",
"12844",
"12845",
"12846",
"12847",
"12848",
"12849",
"12850",
"12851",
"12852",
"12853",
"12854",
"12855",
"12856",
"12857",
"12858",
"12859",
"12860",
"12861",
"12862",
"12863",
"12864",
"12865",
"12866",
"12867",
"12868",
"12869",
"12870",
"12871",
"12872",
"12873",
"12874",
"12875",
"12876",
"12877",
"12878",
"12879",
"12880",
"12881",
"12882",
"12883",
"12884",
"12885",
"12886",
"12887",
"12888",
"12889",
"12890",
"12891",
"12892",
"12893",
"12894",
"12895",
"12896",
"12897",
"12898",
"12899",
"12900",
"12901",
"12902",
"12903",
"12904",
"12905",
"12906",
"12907",
"12908",
"12909",
"12910",
"12911",
"12912",
"12913",
"12914",
"12915",
"12916",
"12917",
"12918",
"12919",
"12920",
"12921",
"12922",
"12923",
"12924",
"12925",
"12926",
"12927",
"12928",
"12929",
"12930",
"12931",
"12932",
"12933",
"12934",
"12935",
"12936",
"12937",
"12938",
"12939",
"12940",
"12941",
"12942",
"12943",
"12944",
"12945",
"12946",
"12947",
"12948",
"12949",
"12950",
"12951",
"12952",
"12953",
"12954",
"12955",
"12956",
"12957",
"12958",
"12959",
"12960",
"12961",
"12962",
"12963",
"12964",
"12965",
"12966",
"12967",
"12968",
"12969",
"12970",
"12971",
"12972",
"12973",
"12974",
"12975",
"12976",
"12977",
"12978",
"12979",
"12980",
"12981",
"12982",
"12983",
"12984",
"12985",
"12986",
"12987",
"12988",
"12989",
"12990",
"12991",
"12992",
"12993",
"12994",
"12995",
"12996",
"12997",
"12998",
"12999",
"13000",
"13001",
"13002",
"13003",
"13004",
"13005",
"13006",
"13007",
"13008",
"13009",
"13010",
"13011",
"13012",
"13013",
"13014",
"13015",
"13016",
"13017",
"13018",
"13019",
"13020",
"13021",
"13022",
"13023",
"13024",
"13025",
"13026",
"13027",
"13028",
"13029",
"13030",
"13031",
"13032",
"13033",
"13034",
"13035",
"13036",
"13037",
"13038",
"13039",
"13040",
"13041",
"13042",
"13043",
"13044",
"13045",
"13046",
"13047",
"13048",
"13049",
"13050",
"13051",
"13052",
"13053",
"13054",
"13055",
"13056",
"13057",
"13058",
"13059",
"13060",
"13061",
"13062",
"13063",
"13064",
"13065",
"13066",
"13067",
"13068",
"13069",
"13070",
"13071",
"13072",
"13073",
"13074",
"13075",
"13076",
"13077",
"13078",
"13079",
"13080",
"13081",
"13082",
"13083",
"13084",
"13085",
"13086",
"13087",
"13088",
"13089",
"13090",
"13091",
"13092",
"13093",
"13094",
"13095",
"13096",
"13097",
"13098",
"13099",
"13100",
"13101",
"13102",
"13103",
"13104",
"13105",
"13106",
"13107",
"13108",
"13109",
"13110",
"13111",
"13112",
"13113",
"13114",
"13115",
"13116",
"13117",
"13118",
"13119",
"13120",
"13121",
"13122",
"13123",
"13124",
"13125",
"13126",
"13127",
"13128",
"13129",
"13130",
"13131",
"13132",
"13133",
"13134",
"13135",
"13136",
"13137",
"13138",
"13139",
"13140",
"13141",
"13142",
"13143",
"13144",
"13145",
"13146",
"13147",
"13148",
"13149",
"13150",
"13151",
"13152",
"13153",
"13154",
"13155",
"13156",
"13157",
"13158",
"13159",
"13160",
"13161",
"13162",
"13163",
"13164",
"13165",
"13166",
"13167",
"13168",
"13169",
"13170",
"13171",
"13172",
"13173",
"13174",
"13175",
"13176",
"13177",
"13178",
"13179",
"13180",
"13181",
"13182",
"13183",
"13184",
"13185",
"13186",
"13187",
"13188",
"13189",
"13190",
"13191",
"13192",
"13193",
"13194",
"13195",
"13196",
"13197",
"13198",
"13199",
"13200",
"13201",
"13202",
"13203",
"13204",
"13205",
"13206",
"13207",
"13208",
"13209",
"13210",
"13211",
"13212",
"13213",
"13214",
"13215",
"13216",
"13217",
"13218",
"13219",
"13220",
"13221",
"13222",
"13223",
"13224",
"13225",
"13226",
"13227",
"13228",
"13229",
"13230",
"13231",
"13232",
"13233",
"13234",
"13235",
"13236",
"13237",
"13238",
"13239",
"13240",
"13241",
"13242",
"13243",
"13244",
"13245",
"13246",
"13247",
"13248",
"13249",
"13250"
]
````

4. Run Set-AzPolicySetDefinition in your local. It'll return InternalServerError : Encountered internal server error. 
````
$initiative = Get-AzPolicySetDefinition -ResourceId "ENTER RESOURCE ID"
$metadata = @{category = $initative.Properties.Metadata.category
        version            = $initative.Properties.Metadata.version 
    } | ConvertTo-Json
    Write-Output "Updating Initiative with the new values"
    Set-AzPolicySetDefinition -InputObject $initiative -Metadata $metadata
````
When I significantly reduce the number of policy and their parameters value, the cmdlet works just fine. 

### Script or Debug output

```PowerShell
InternalServerError : Encountered internal server error. Diagnostic information: timestamp '20221124T154930Z', subscription id '', tracking id '7c6b0c5c-fa26-4a8c-ae48-94ceb0065bfe', request correlation id '7c6b0c5c-fa26-4a8c-ae48-94ceb0065bfe'.
CorrelationId: 7c6b0c5c-fa26-4a8c-ae48-94ceb0065bfe
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.4.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
Message        : InternalServerError : Encountered internal server error. Diagnostic information: timestamp '20221124T154930Z', subscription id '', tracking id '7c6b 
                 0c5c-fa26-4a8c-ae48-94ceb0065bfe', request correlation id '7c6b0c5c-fa26-4a8c-ae48-94ceb0065bfe'.
                 CorrelationId: 7c6b0c5c-fa26-4a8c-ae48-94ceb0065bfe
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedExcept 
                 ion)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {Set-AzPolicySetDefinition}
Line           :     Set-AzPolicySetDefinition -InputObject $initative -Metadata $metadata
Position       : At line:5 char:5
                 +     Set-AzPolicySetDefinition -InputObject $initative -Metadata $meta …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 45
```

**Comment by rachelxj-ms** [comment]
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#azure-policy-limits
Policy definition, initiative, or assignment request body | Bytes | 1,048,576

**Comment by rachelxj-ms** [comment]
The issue has been addressed in #20252

**Comment by falmirayasmin** [comment]
Hi Rachel, I'm still facing the same issue.

**Comment by BethanyZhou** [comment]
Hi @falmirayasmin , please expect the fix available on Dec 6th.

**Comment by falmirayasmin** [comment]
Thank you!

**Comment by rachelxj-ms** [comment]
There was a mistake in previous fix, refix this issue.

**Comment by falmirayasmin** [comment]
> There was a mistake in previous fix, refix this issue.
thank you for the update, when can I expect the new fix to be available?

**Comment by falmirayasmin** [comment]
Just to verify, the refix is not yet available, right? I still see the same issue

**Comment by dingmeng-xue** [comment]
We will publish hotfix by the early next week.

**Comment by falmirayasmin** [comment]
Has the update been published? I still see the same issue

**Comment by dingmeng-xue** [comment]
@falmirayasmin , please share new debug information. We need all information about request url and attributes in request header.

**Comment by falmirayasmin** [comment]
Script or Debug output:
##[error]InvalidRequestContent : The request content could not be read. Internal error: 'Request body too large. The max request body size is 1048576 bytes.'.
