### ISSUE TITLE
Get-AzIotHub throws error converting value "RootCertificateV2" to type 'Microsoft.Azure.Commands.Management.IotHub.Models.PSCapabilities'

### ISSUE THREAD

**Issue by jochemdevos** [Azure/azure-powershell#20846]
### Description

Get-AzIotHub throws error converting value "RootCertificateV2" to type 'Microsoft.Azure.Commands.Management.IotHub.Models.PSCapabilities'

This happens on Iothubs that have been migrated to the new Digicert root certificate.

Workaround; revert back to Baltimore root certificate ; Get-AzIothub will work again

### Issue script & Debug output

```PowerShell
Get-AzIotHub : Error converting value "RootCertificateV2" to type 'Microsoft.Azure.Commands.Management.IotHub.Models.PSCapabilities'. Path '[0].Properties.Features', line 1, position 1763.
At line:1 char:1
+ Get-AzIotHub
+ ~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzIotHub], JsonSerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.IotHub.GetAzureRmIotHub

DEBUG: AzureQoSEvent: Module: Az.IotHub:2.7.3; CommandName: Get-AzIotHub; PSVersion: 5.1.22000.1335; IsSuccess: False; Duration: 00:00:01.6565163; Exception: Error converting value "RootCertificateV2" to type 'Microsoft.Azure.Commands.Management.IotHub.Models.PSCapabilities'. Path
 '[0].Properties.Features', line 1, position 1763.;
DEBUG: Finish sending metric.
DEBUG: 16:42:05 - GetAzureRmIotHub end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.1335
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.1335
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Occurs with Az 7.5 , 7.7 and 9.3
```

### Error output

```PowerShell
Resolve-AzError
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use
`Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.


   HistoryId: 1


Message        : Error converting value "RootCertificateV2" to type
                 'Microsoft.Azure.Commands.Management.IotHub.Models.PSCapabilities'. Path '[0].properties.features',
                 line 1, position 1789.
StackTrace     :    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType,
                 Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter
                 converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty
                 property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty
                 containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject,
                 JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type
                 objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract,
                 JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader
                 reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty
                 property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty
                 containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject,
                 JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type
                 objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract,
                 JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader
                 reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader
                 reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type
                 objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader
                 reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type
                 objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings
                 settings)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
                    at Microsoft.Azure.Commands.Management.IotHub.GetAzureRmIotHub.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Newtonsoft.Json.JsonSerializationException
InvocationInfo : {Get-AzIotHub}
Line           : Get-AzIotHub
Position       : At line:1 char:1
                 + Get-AzIotHub
                 + ~~~~~~~~~~~~
HistoryId      : 1

Message        : Requested value 'RootCertificateV2' was not found.
StackTrace     :    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy,
                 String value, Boolean disallowNumber)
                    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType,
                 Object existingValue, JsonSerializer serializer)
Exception      : System.ArgumentException
InvocationInfo : {Get-AzIotHub}
Line           : Get-AzIotHub
Position       : At line:1 char:1
                 + Get-AzIotHub
                 + ~~~~~~
```

**Comment by navba-MSFT** [comment]
@jochemdevos Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jochemdevos I am checking if this is a known issue with the IOT PS cmdlets. In the meantime, could you please run the [Azure CLI IOT Hub command](https://learn.microsoft.com/en-us/cli/azure/iot/hub?view=azure-cli-latest) to check if that serves your purpose ? Awaiting your reply.

**Comment by jochemdevos** [comment]
During development as a workaround I have reverted the testing iothub to the old baltimore certificate.

**Comment by navba-MSFT** [comment]
@jochemdevos Thanks for your reply. I am discussing this issue internally with the Product owners. I will keep you posted about the updates once I hear from them.

**Comment by navba-MSFT** [comment]
@jochemdevos Could you please confirm if you are using the [most recent version](https://www.powershellgallery.com/packages/Az.IotHub/2.7.4) of `Az.IotHub`  module ?

**Comment by jochemdevos** [comment]
Hi, yes, confirmed:

Get-InstalledModule -Name 'Az.Iothub'

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.7.4      Az.IotHub                           PSGallery            Microsoft Azure PowerShell - IoT Hub service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....

**Comment by navba-MSFT** [comment]
@jochemdevos Is your resource located in West Europe region ?

**Comment by jochemdevos** [comment]
it occurs with iothubs in west europe as well as north europe

**Comment by navba-MSFT** [comment]
@jochemdevos Thanks for your reply. I have shared this info with the Product Owners. This issue should be fixed by eod today or tomorrow. Post that you can test the same command again.

**Comment by jochemdevos** [comment]
So what's the timeline on it? I see the module generally has monthly updates, will it be included? Or is a 'hotfix' release possible?

**Comment by navba-MSFT** [comment]
@jochemdevos The work is completed. I am checking this internally on when / how the fix would be publicly available. I will keep you posted.

**Comment by navba-MSFT** [comment]
@jochemdevos I have got an update from the Product Owners that the fix is in place and it should be available in next release in March 7th.

**Comment by jochemdevos** [comment]
/unresolve

Still have this issue, even with Az.Iothub 2.7.5

```
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.7.5      Az.IotHub                           PSGallery            Microsoft Azure PowerShell - IoT Hub service cmd...
```

``` 
Get-AzIotHub -ResourceGroupName $IoTHubResourceGroupName -Name $IoTHubName
Get-AzIotHub : Error converting value "RootCertificateV2" to type
'Microsoft.Azure.Commands.Management.IotHub.Models.PSCapabilities'. Path 'properties.features', line 1, position 5806.
At line:1 char:1
+ Get-AzIotHub -ResourceGroupName $IoTHubResourceGroupName -Name $IoTHu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzIotHub], JsonSerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.IotHub.GetAzureRmIotHub
```

**Comment by navba-MSFT** [comment]
Adding service team to look into this.

**Comment by jochemdevos** [comment]
hi, any update..?

**Comment by konradg1989** [comment]
Hi. After switching to new G2 certificate I'm facing the same issue but with "Set-AzIotHub"

![image](https://github.com/Azure/azure-powershell/assets/12032784/5c989400-a4b5-4555-afb8-e339773447a6)


I think that now (after permanent switch to the new cert) it will be a global problem.

**Comment by lorena84** [comment]
Hi, 
Getting the same error with Set-AzureRmIotHub command... As @konradg1989 said, this is going to be a global problem.
BR
Lorena

**Comment by nnabueze** [comment]
@ethanann-ms Am new to powershell, how do i update to az version 10.3.0 to resolve this issue.
