### ISSUE TITLE
Get-AzRoleAssignment: Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by mblaschke-daimlertruck** [Azure/azure-powershell#24177]
### Description

In Azure China when trying to get roleAssignments via `Get-AzRoleAssignment -Scope $managementGroupId` the cmdlet fails with:

```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```

### Issue script & Debug output

```PowerShell
Get-AzRoleAssignment -Scope /providers/Microsoft.Management/managementGroups/xxxxx
Get-AzRoleAssignment -Scope /subscriptions/xxxxx
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.11
PSEdition                      Core
GitCommitId                    7.3.11
OS                             Linux 5.15.0-1051-azure #59-Ubuntu SMP Wed Oct 11 18:49:16 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     11.3.1                Az                                  Core,Desk
Script     2.15.1                Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCo…
Script     2.9.1                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCo…
Script     2.0.0                 Az.Advisor                          Core,Desk {Disable-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Get…
Script     6.0.1                 Az.Aks                              Core,Desk {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, Get-AzAksNo…
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, G…
Script     4.0.2                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Ad…
Script     1.0.0                 Az.App                              Core,Desk {Disable-AzContainerAppRevision, Enable-AzContainerAppRevision, Get-A…
Script     1.3.0                 Az.AppConfiguration                 Core,Desk {Get-AzAppConfigurationStore, Get-AzAppConfigurationStoreKey, New-AzA…
Script     2.2.3                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzAp…
Script     1.0.0                 Az.ArcResourceBridge                Core,Desk {Get-AzArcResourceBridge, Get-AzArcResourceBridgeApplianceCredential,…
Script     2.0.0                 Az.Attestation                      Core,Desk {Get-AzAttestationPolicy, Set-AzAttestationPolicy, Reset-AzAttestatio…
Script     1.0.0                 Az.Automanage                       Core,Desk {Get-AzAutomanageBestPractice, Get-AzAutomanageConfigProfile, Get-AzA…
Script     1.10.0                Az.Automation                       Core,Desk {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeRepor…
Script     3.5.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, Ne…
Script     2.0.3                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, …
Script     3.1.1                 Az.Cdn                              Core,Desk {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdnEndpointContent, Dis…
Script     2.0.0                 Az.CloudService                     Core,Desk {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-AzCloudServi…
Script     1.14.1                Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, G…
Script     7.1.1                 Az.Compute                          Core,Desk {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, A…
Script     1.0.0                 Az.ConfidentialLedger               Core,Desk {Get-AzConfidentialLedger, New-AzConfidentialLedger, New-AzConfidenti…
Script     4.0.0                 Az.ContainerInstance                Core,Desk {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-AzContainer…
Script     4.1.3                 Az.ContainerRegistry                Core,Desk {Connect-AzContainerRegistry, Get-AzContainerRegistryManifest, Get-Az…
Script     1.14.0                Az.CosmosDB                         Core,Desk {Get-AzCosmosDBAccount, Get-AzCosmosDBAccountKey, Get-AzCosmosDBCassa…
Script     0.3.1                 Az.CostManagement                   Core,Desk {Get-AzCostManagementExport, Get-AzCostManagementExportExecutionHisto…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeD…
Script     1.7.1                 Az.Databricks                       Core,Desk {Get-AzDatabricksAccessConnector, Get-AzDatabricksOutboundNetworkDepe…
Script     1.18.1                Az.DataFactory                      Core,Desk {Add-AzDataFactoryV2DataFlowDebugSessionPackage, Add-AzDataFactoryV2T…
Script     1.0.3                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCre…
Script     1.3.0                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedI…
Script     2.2.0                 Az.DataProtection                   Core,Desk {Backup-AzDataProtectionBackupInstanceAdhoc, Edit-AzDataProtectionPol…
Script     1.0.1                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-AzDataShareAc…
Script     4.3.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-AzWvdApplica…
Script     1.1.0                 Az.DevCenter                        Core,Desk {Deploy-AzDevCenterUserEnvironment, Get-AzDevCenterAdminAttachedNetwo…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDt…
Script     1.2.0                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Se…
Script     1.0.0                 Az.ElasticSan                       Core,Desk {Add-AzElasticSanVolumeGroupNetworkRule, Get-AzElasticSan, Get-AzElas…
Script     1.6.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, Ne…
Script     4.2.0                 Az.EventHub                         Core,Desk {New-AzEventHubAuthorizationRuleSASToken, Approve-AzEventHubPrivateEn…
Script     1.10.0                Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoo…
Script     4.0.7                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctio…
Script     6.1.0                 Az.HDInsight                        Core,Desk {Add-AzHDInsightClusterIdentity, Add-AzHDInsightComponentVersion, Add…
Script     2.0.0                 Az.HealthcareApis                   Core,Desk {Get-AzHealthcareApisService, Get-AzHealthcareApisWorkspace, Get-AzHe…
Script     2.7.5                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConn…
Script     5.2.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzK…
Script     2.3.0                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabasePrincipal, G…
Script     1.0.0                 Az.LoadTesting                      Core,Desk {Get-AzLoad, New-AzLoad, Remove-AzLoad, Update-AzLoad}
Script     1.5.0                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly,…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-A…
Script     1.0.0                 Az.MachineLearningServices          Core,Desk {Get-AzMLServiceQuota, Get-AzMLServiceUsage, Get-AzMLServiceVMSize, G…
Script     1.4.1                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceC…
Script     1.2.0                 Az.ManagedServiceIdentity           Core,Desk {Get-AzSystemAssignedIdentity, Get-AzUserAssignedIdentity, Get-AzUser…
Script     3.0.0                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, Get-AzManagedServicesDefinition, Ge…
Script     2.0.0                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Invoke-AzMarketplaceSignTerms, Set-AzMarketp…
Script     1.1.2                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaSer…
Script     2.3.0                 Az.Migrate                          Core,Desk {Get-AzMigrateDiscoveredServer, Get-AzMigrateHCIJob, Get-AzMigrateHCI…
Script     5.0.1                 Az.Monitor                          Core,Desk {Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2, Ad…
Script     1.1.1                 Az.MySql                            Core,Desk {Get-AzMySqlConfiguration, Get-AzMySqlConnectionString, Get-AzMySqlFi…
Script     7.4.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplication…
Script     1.0.0                 Az.NetworkCloud                     Core,Desk {Deploy-AzNetworkCloudCluster, Disable-AzNetworkCloudStorageAppliance…
Script     1.0.0                 Az.Nginx                            Core,Desk {Get-AzNginxCertificate, Get-AzNginxConfiguration, Get-AzNginxDeploym…
Script     1.1.2                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-A…
Script     3.2.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperation…
Script     1.6.4                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-…
Script     1.1.0                 Az.PostgreSql                       Core,Desk {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlConnectionString, Get…
Script     2.0.0                 Az.PowerBIEmbedded                  Core,Desk {Resume-AzPowerBIEmbeddedCapacity, Suspend-AzPowerBIEmbeddedCapacity,…
Script     1.0.4                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone,…
Script     6.7.1                 Az.RecoveryServices                 Core,Desk {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Backup-AzReco…
Script     1.8.1                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get…
Script     1.2.0                 Az.RedisEnterpriseCache             Core,Desk {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache, Get-AzRed…
Script     2.0.0                 Az.Relay                            Core,Desk {Get-AzRelayAuthorizationRule, Get-AzRelayHybridConnection, Get-AzRel…
Script     0.13.0                Az.ResourceGraph                    Core,Desk {Search-AzGraph, Get-AzResourceGraphQuery, New-AzResourceGraphQuery, …
Script     1.2.0                 Az.ResourceMover                    Core,Desk {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveCollection, …
Script     6.15.1                Az.Resources                        Core,Desk {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment,…
Script     0.10.0                Az.Search                           Core,Desk {New-AzSearchService, Get-AzSearchService, Set-AzSearchService, Remov…
Script     1.5.1                 Az.Security                         Core,Desk {Get-AzSecuritySolution, Get-AzSecuritySolutionsReferenceData, New-Az…
Script     3.1.1                 Az.SecurityInsights                 Core,Desk {Get-AzSentinelAlertRule, Get-AzSentinelAlertRuleAction, Get-AzSentin…
Script     3.0.0                 Az.ServiceBus                       Core,Desk {New-AzServiceBusAuthorizationRuleSASToken, Test-AzServiceBusNameAvai…
Script     3.3.2                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricManagedClus…
Script     2.0.0                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     4.14.0                Az.Sql                              Core,Desk {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlElasticJobStep, Add-AzSql…
Script     2.2.0                 Az.SqlVirtualMachine                Core,Desk {Get-AzAvailabilityGroupListener, Get-AzSqlVM, Get-AzSqlVMGroup, Invo…
Script     2.3.0                 Az.StackHCI                         Core,Desk {Add-AzStackHCIVMAttestation, Disable-AzStackHCIAttestation, Disable-…
Script     1.0.0                 Az.StackHCIVM                       Core,Desk {Add-AzStackHCIVMVirtualMachineDataDisk, Add-AzStackHCIVMVirtualMachi…
Script     6.1.1                 Az.Storage                          Core,Desk {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPol…
Script     1.3.0                 Az.StorageMover                     Core,Desk {Get-AzStorageMover, Get-AzStorageMoverAgent, Get-AzStorageMoverEndpo…
Script     2.1.1                 Az.StorageSync                      Core,Desk {Get-AzStorageSyncCloudEndpoint, Get-AzStorageSyncGroup, Get-AzStorag…
Script     2.0.0                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsClusterStreamingJ…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSupp…
Script     3.0.5                 Az.Synapse                          Core,Desk {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTriggerSubscr…
Script     1.2.2                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerC…
Script     3.2.0                 Az.Websites                         Core,Desk {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppTrafficRouting, Edit-…
Manifest   2.1.0                 AzTable                             Desk      {Add-AzTableRow, Get-AzTableRow, Get-AzTableRowAll, Get-AzTableRowByP…
Script     1.0.0                 EPS                                 Desk      Invoke-EpsTemplate
Manifest   2.14.0                Microsoft.Graph                     Core,Desk
Script     2.14.0                Microsoft.Graph.Applications        Core,Desk {Add-MgApplicationKey, Add-MgApplicationPassword, Add-MgServicePrinci…
Script     2.14.0                Microsoft.Graph.Authentication      Core,Desk {Connect-MgGraph, Disconnect-MgGraph, Get-MgContext, Invoke-MgGraphRe…
Script     2.14.0                Microsoft.Graph.Bookings            Core,Desk {Get-MgBookingBusiness, Get-MgBookingBusinessAppointment, Get-MgBooki…
Script     2.14.0                Microsoft.Graph.Calendar            Core,Desk {Get-MgGroupCalendar, Get-MgGroupCalendarEvent, Get-MgGroupCalendarPe…
Script     2.14.0                Microsoft.Graph.ChangeNotifications Core,Desk {Get-MgSubscription, Invoke-MgReauthorizeSubscription, New-MgSubscrip…
Script     2.14.0                Microsoft.Graph.CloudCommunications Core,Desk {Add-MgCommunicationCallLargeGalleryView, Clear-MgCommunicationPresen…
Script     2.14.0                Microsoft.Graph.Compliance          Core,Desk {Get-MgCompliance, Get-MgPrivacySubjectRightsRequest, Get-MgPrivacySu…
Script     2.14.0                Microsoft.Graph.CrossDeviceExperie… Core,Desk {Get-MgUserActivity, Get-MgUserActivityCount, Get-MgUserActivityHisto…
Script     2.14.0                Microsoft.Graph.DeviceManagement    Core,Desk {Get-MgAdminEdge, Get-MgAdminEdgeInternetExplorerMode, Get-MgAdminEdg…
Script     2.14.0                Microsoft.Graph.DeviceManagement.A… Core,Desk {Clear-MgDeviceManagementManagedDevice, Disable-MgDeviceManagementMan…
Script     2.14.0                Microsoft.Graph.DeviceManagement.A… Core,Desk {Get-MgDeviceManagementApplePushNotificationCertificate, Get-MgDevice…
Script     2.14.0                Microsoft.Graph.DeviceManagement.E… Core,Desk {Get-MgDeviceManagementConditionalAccessSetting, Get-MgDeviceManageme…
Script     2.14.0                Microsoft.Graph.DeviceManagement.F… Core,Desk {Confirm-MgDeviceManagementWindowsEnrollmentAutoDiscovery, Get-MgDevi…
Script     2.14.0                Microsoft.Graph.Devices.CloudPrint  Core,Desk {Get-MgPrint, Get-MgPrintConnector, Get-MgPrintConnectorCount, Get-Mg…
Script     2.14.0                Microsoft.Graph.Devices.CorporateM… Core,Desk {Get-MgDeviceAppManagement, Get-MgDeviceAppManagementAndroidManagedAp…
Script     2.14.0                Microsoft.Graph.Devices.ServiceAnn… Core,Desk {Get-MgServiceAnnouncementHealthOverview, Get-MgServiceAnnouncementHe…
Script     2.14.0                Microsoft.Graph.DirectoryObjects    Core,Desk {Confirm-MgDirectoryObjectMemberGroup, Confirm-MgDirectoryObjectMembe…
Script     2.14.0                Microsoft.Graph.Education           Core,Desk {Get-MgEducationClass, Get-MgEducationClassAssignment, Get-MgEducatio…
Script     2.14.0                Microsoft.Graph.Files               Core,Desk {Add-MgDriveListContentTypeCopy, Add-MgDriveListContentTypeCopyFromCo…
Script     2.14.0                Microsoft.Graph.Groups              Core,Desk {Add-MgGroupDriveListContentTypeCopy, Add-MgGroupDriveListContentType…
Script     2.14.0                Microsoft.Graph.Identity.Directory… Core,Desk {Confirm-MgContactMemberGroup, Confirm-MgContactMemberObject, Confirm…
Script     2.14.0                Microsoft.Graph.Identity.Governance Core,Desk {Add-MgIdentityGovernanceAccessReviewDefinitionInstanceDecision, Get-…
Script     2.14.0                Microsoft.Graph.Identity.Partner    Core,Desk {Get-MgTenantRelationshipDelegatedAdminCustomer, Get-MgTenantRelation…
Script     2.14.0                Microsoft.Graph.Identity.SignIns    Core,Desk {Confirm-MgRiskyServicePrincipalCompromised, Confirm-MgRiskyUserCompr…
Script     2.14.0                Microsoft.Graph.Mail                Core,Desk {Get-MgUserInferenceClassification, Get-MgUserInferenceClassification…
Script     2.14.0                Microsoft.Graph.Notes               Core,Desk {Get-MgGroupOnenoteNotebook, Get-MgGroupOnenoteNotebookCount, Get-MgG…
Script     2.14.0                Microsoft.Graph.People              Core,Desk {Get-MgUserLastSharedMethodInsight, Get-MgUserPerson, Get-MgUserPerso…
Script     2.14.0                Microsoft.Graph.PersonalContacts    Core,Desk {Get-MgUserContact, Get-MgUserContactCount, Get-MgUserContactExtensio…
Script     2.14.0                Microsoft.Graph.Planner             Core,Desk {Get-MgGroupPlanner, Get-MgGroupPlannerPlan, Get-MgGroupPlannerPlanBu…
Script     2.14.0                Microsoft.Graph.Reports             Core,Desk {Export-MgReportPartnerBillingUsageBilled, Export-MgReportPartnerBill…
Script     2.14.0                Microsoft.Graph.SchemaExtensions    Core,Desk {Get-MgSchemaExtension, Get-MgSchemaExtensionCount, New-MgSchemaExten…
Script     2.14.0                Microsoft.Graph.Search              Core,Desk {Add-MgExternalConnectionItemActivity, Get-MgExternal, Get-MgExternal…
Script     2.14.0                Microsoft.Graph.Security            Core,Desk {Add-MgSecurityCaseEdiscoveryCaseCustodianHold, Add-MgSecurityCaseEdi…
Script     2.14.0                Microsoft.Graph.Sites               Core,Desk {Add-MgSite, Add-MgSiteContentTypeCopy, Add-MgSiteContentTypeCopyFrom…
Script     2.14.0                Microsoft.Graph.Teams               Core,Desk {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMember, Add-MgT…
Script     2.14.0                Microsoft.Graph.Users               Core,Desk {Get-MgUser, Get-MgUserCount, Get-MgUserCreatedObject, Get-MgUserCrea…
Script     2.14.0                Microsoft.Graph.Users.Actions       Core,Desk {Add-MgUserChatMember, Add-MgUserDriveListContentTypeCopy, Add-MgUser…
Script     2.14.0                Microsoft.Graph.Users.Functions     Core,Desk {Export-MgUserDeviceAndAppManagementData, Get-MgAllUserChatMessage, G…
Manifest   3.1.3                 Posh-SSH                            Desk      {Get-SCPItem, Get-SFTPItem, New-SFTPSession, New-SSHSession…}
Script     0.4.7                 powershell-yaml                     Desk      {ConvertTo-Yaml, ConvertFrom-Yaml, cfy, cty}
Binary     0.8.1                 SHiPS                               Desk
Script     22.2.0                SqlServer                           Core,Desk {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvailabilityGrou…
Script     0.2.1                 Trackyon.Utils                      Desk      {Backup-Location, Get-OperatingSystem, New-Directory, Set-As…}
Script     7.15.2                VSTeam                              Core,Desk {Add-VSTeam, Add-VSTeamAccessControlEntry, Add-VSTeamArea, Add-VSTeam…

    Directory: /opt/microsoft/powershell/7/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-ExecutionPolicy, ConvertFro…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
Script     1.4.8.1               PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource…}
Script     2.2.5                 PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability…}
Script     2.2.6                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLin…
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob
```

### Error output

```PowerShell
Message        : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
StackTrace     :    at System.Collections.Generic.List`1.get_Item(Int32 index)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClientExtensions.ToPSRoleDefinition(RoleDefinition role)
                    at
                 Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.<>c.<ListRoleDefinitionsForScope>b__14_0(RoleDefinition
                 r)
                    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
                    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
                    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClientExtensions.ToPSRoleAssignments(IEnumerable`1
                 assignments, AuthorizationClient policyClient, ActiveDirectoryClient activeDirectoryClient, String scopeForRoleDefinitions)
                    at
                 Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.FilterRoleAssignments(FilterRoleAssignmentsOptions
                 options, String currentSubscription, UInt64 first, UInt64 skip)
                    at Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentOutOfRangeException
InvocationInfo : {Get-AzRoleAssignment}
Line           :     Get-AzRoleAssignment -Scope $Scope | ? Scope -Eq $Scope | ForEach-Object {

Position       : At /xxxxx/infrastructure/.includes/resources.ps1:173 char:5
                 +     Get-AzRoleAssignment -Scope $Scope | ? Scope -Eq $Scope | ForEach …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 15
```

**Comment by john-crouch** [comment]
I can confirm that this is also affecting Azure USGov subscriptions.

**Comment by NoriZC** [comment]
@john-crouch Have you tried to use a previous version again to see if the issue can be reproduced? Or it worked at the time you were using Az 11.2.0?

**Comment by NoriZC** [comment]
@mumoryan I located the issue in [this file](https://github.com/mumoryan/azure-powershell/blob/678364a36d32a7deaf39178cbcf20fa62d8db47c/src/Resources/Resources/Models.Authorization/AuthorizationClientExtensions.cs) and found [this pr](https://github.com/Azure/azure-powershell/pull/23904) might be the cause. Could you help fix it?

**Comment by WKevinDavis** [comment]
Any resolution with this error yet for this cmdlet?

**Comment by mumoryan** [comment]
@NoriZC Unfortunately I no longer work at the owning team. I'd suggest reaching out directly. + @veseshad92 for triage

**Comment by sbebrys** [comment]
I have the same issue in Azure China and I confirmed that problem caused by version 6.13.0 of Az.Resources - 6.12.1 works fine.

**Comment by TL-KevinDavis** [comment]
Hello??? Is anyone there?
Are we reporting this issue in the correct place?????

**Comment by NoriZC** [comment]
@mumoryan  @veseshad92 Could you please help check this issue? Or we will simple revert your pr to see if customers could be unblocked.

**Comment by veseshad92** [comment]
Thank you for reaching out. I will look and get back to you.

Thanks
venky

**Comment by veseshad92** [comment]
Created PR which is a potential fix https://github.com/Azure/azure-powershell/pull/24384

**Comment by NoriZC** [comment]
Hi @mblaschke-daimlertruck @TL-KevinDavis @sbebrys Could you help check whether the error is fixed in this package?   
How to install:
  - Install the Az.Tools.Installer module.
      ```powershell
      Install-Module -Name Az.Tools.Installer -Repository PSGallery
      ```
  - Install the latest Az.Accounts module unless the Eng build requires a specific version.
      ```powershell
      Install-Module Az.Accounts -Repository PSGallery
      ```
  - Use Az.Tools.Installer to install the Eng build.
      ```powershell
      https://azposhpreview.blob.core.windows.net/public/Az.Resources.6.16.0.nupkg
      ```

**Comment by TL-KevinDavis** [comment]
I have successfully installed ALL of the Az module and this command is not installing the NuGet package.
----
Install-AzModule -Path "https://azposhpreview.blob.core.windows.net/public/Az.Resources.6.16.0.nupkg" -repository PSGallery -Force  
----
Error:
----
Install-AzModule : The 'Install-AzModule' command was found in the module 'Az.Tools.Installer', but the module could not be loaded. For more information, run 'Import-Module Az.Tools.Installer'.

**Comment by NoriZC** [comment]
> ## I have successfully installed ALL of the Az module and this command is not installing the NuGet package.
> ## `Install-AzModule -Path "https://azposhpreview.blob.core.windows.net/public/Az.Resources.6.16.0.nupkg" -repository PSGallery -Force `
> ## Error:
> `Install-AzModule : The 'Install-AzModule' command was found in the module 'Az.Tools.Installer', but the module could not be loaded. For more information, run 'Import-Module Az.Tools.Installer'.`

Have you installed and imported `Az.Tools.Installer`?

**Comment by TL-KevinDavis** [comment]
Imported both the `Az.Tools.Installer` module as well as the `Az.Accounts` module.
I then imported the entire `Az` module and still received the same error.

**Comment by NoriZC** [comment]
@TL-KevinDavis 
I have run the 3 commands one by one as above, everything goes well. Could you reopen powershell console and skip installing the whole Az part. And see whether the error occurs again?
![image](https://github.com/Azure/azure-powershell/assets/110961157/fb98dc58-9b6b-4d30-8cf2-223ec0a6d07c)

**Comment by brnwn4** [comment]
Also effecting Azure USGov Tenants..

**Comment by NoriZC** [comment]
> Same error: Not behind a firewall. Running as Administrator.
> 
> PS C:\WINDOWS\system32> Install-Module -Name Az.Tools.Installer -Repository PSGallery Install-Module Az.Accounts -Repository PSGallery Install-AzModule -Path https://azposhpreview.blob.core.windows.net/public/Az.Resources.6.16.0.nupkg Install-AzModule : The 'Install-AzModule' command was found in the module 'Az.Tools.Installer', but the module could not be loaded. For more information, run 'Import-Module Az.Tools.Installer'. At line:3 char:1
> 
> * Install-AzModule -Path  https://azposhpreview.blob.core.windows.net/p ...
> * ```
>     + CategoryInfo          : ObjectNotFound: (Install-AzModule:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
>   ```

Could you try running `Import-Module Az.Tools.Installer` and see what happens?

**Comment by TL-KevinDavis** [comment]
That was the first command in my previous post. 
That command succeeds as well as the command to `Install-Module Az.Accounts -Repository PSGallery`.
The command that fails is the `Install-AzModule` command.
That command fails with the response:
"Install-AzModule : The 'Install-AzModule' command was found in the module 'Az.Tools.Installer', but the module could not be loaded. For more information, run 'Import-Module Az.Tools.Installer'. At line:3 char:1"

**Comment by veseshad92** [comment]
> Also effecting Azure USGov Tenants..

Can you please share the stack trace as well..

**Comment by NoriZC** [comment]
> That was the first command in my previous post. That command succeeds as well as the command to `Install-Module Az.Accounts -Repository PSGallery`. The command that fails is the `Install-AzModule` command. That command fails with the response: "Install-AzModule : The 'Install-AzModule' command was found in the module 'Az.Tools.Installer', but the module could not be loaded. For more information, run 'Import-Module Az.Tools.Installer'. At line:3 char:1"

Could you help try the work around for this command:
- Download the nuget package from https://azposhpreview.blob.core.windows.net/public/Az.Resources.6.16.0.nupkg
- Register local Repository
 ```
Register-PSRepository -Name PSDrop -SourceLocation <your pkg location> -PackageManagementProvider Nuget -InstallationPolicy Trusted
```
- Install manually 
```
Install-Module -Scope CurrentUser -Name Az.Resources -Repository PSDrop -Force
```

**Comment by brnwn4** [comment]
I believe this issue is fixed.

**Comment by TL-KevinDavis** [comment]
I also was able to execute the 'Install-AzModule' command on a US Gov Azure server.

**Comment by veseshad92** [comment]
> I also was able to execute the 'Install-AzModule' command on a US Gov Azure server.

Did you try running your getroleassignment command that was failing previously ? Is the issue fixed?

**Comment by TL-KevinDavis** [comment]
Sorry, I did not, and that function is still failing.

**Comment by TL-KevinDavis** [comment]
Sorry I forgot that was the original issue.
That cmdlet still fails:
`> $ResourceScope                                                                                                                               /subscriptions/12d81ff1-> > > 3**b-4**2-****-97f2c*****60/resourceGroups/****/providers/Microsoft.Sql/servers/****db
> Get-AzRoleAssignment | Where-Object {$_.Scope -eq $ResourceScope}                                                                            
> Get-AzRoleAssignment: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`

**Comment by veseshad92** [comment]
> Sorry I forgot that was the original issue. That cmdlet still fails:
> 
> > $ResourceScope
> > /subscriptions/12d81ff1_**3**b-4__2-****-97f2c_****60/resourceGroups/****/providers/Microsoft.Sql/servers/****db
> > Get-AzRoleAssignment | Where-Object {$_.Scope -eq $ResourceScope}
> > Get-AzRoleAssignment: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

Is it with the new version that was give or still old version?

**Comment by TL-KevinDavis** [comment]
It is with whatever version is loaded when the install command is issued from an Azure Cloud Shell.
If I am supposed to download this Nuget Package to the Azure Server to install I need a link with detailed instructions on how to perform those actions.

**Comment by NoriZC** [comment]
Hi Everyone, we have already released the possible fix.

Please try `Install-Module -Name Az.Resources -RequiredVersion 6.16.1` to install the latest Az.Resources to see whether this issue is fixed or not.

**Comment by tssganesh** [comment]
Hi Everyone, with Az.Resources 6.16.1 version, observing the same issue in Azure Gov Cloud. 
Get-AzRoleAssignment : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

**Comment by grdederick** [comment]
Seeing the same issue in AzureGov on 6.16.1 still.

Using the 7.0.0 preview version works though.

**Comment by christian-vorhemus** [comment]
@NoriZC I still face this error running `Get-AzRoleAssignment -Scope "/"` (but actually any scope I tried didn't work) in the Dogfood environment with Az.Resources 7.1.0 installed.

**Comment by Icybiubiubiu** [comment]
tested with old version az.resource module resolved this issue.
Install-Module -Name Az.Resources -RequiredVersion 6.11.1

**Comment by isra-fel** [comment]
@Icybiubiubiu could you share with Azure environment did you get trouble with? Was it the public cloud, pre-production, or regional cloud?

**Comment by veseshad92** [comment]
https://github.com/Azure/azure-powershell/pull/25681
