### ISSUE TITLE
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.

### ISSUE THREAD

**Issue by abhishekanand** [Azure/azure-powershell#2605]
AzureRM version 1.5.1
Get resources by resource group does not work 

PS C:\Users\user> Get-AzureRmResourceGroup
ResourceGroupName : FTASRVaultRG
Location          : eastus
ProvisioningState : Succeeded
Tags              : 
ResourceId        : /subscriptions/6b6a59a6-e367-4913-bea7-34b6862095bf/resourceGroups/FTASRVaultRG

ResourceGroupName : mygroup2
Location          : centralus
ProvisioningState : Succeeded
Tags              : 
ResourceId        : /subscriptions/6b6a59a6-e367-4913-bea7-34b6862095bf/resourceGroups/mygroup2
# 

PS C:\Users\user> Get-AzureRmResource -ResourceGroupName mygroup2
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
- Get-AzureRmResource -ResourceGroupName mygroup2
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
  - FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

**Comment by markcowl** [comment]
@vivsriaus can you take a look?

**Comment by vivsriaus** [comment]
@abhishekanand this is not an issue with the cmdlet, this is by design. That said, we're currently evaluating options to list resources under a resource group, and to add support for this in one of our ARM cmdlets. 

In the meantime, please use Find-AzureRmResource -ResourceGroupNameContains "myGroup" as a workaround. Cc/ @ravbhatnagar

**Comment by ravbhatnagar** [comment]
#2307

**Comment by raycrawford** [comment]
Is it really by design?  ResourceGroupName is a named parameter of Get-AzureRmResource and yet even when a Resource Group Name is explicitly given, it still results in:

`
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRmResource -ResourceGroupName 'AZ-NA-EASTUS2-Network'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation. 
   GetAzureResourceCmdlet
`
What is the ETA to resolve this bug?

**Comment by ravbhatnagar** [comment]
This will be fixed in December release of PS. Exact name matches will be supported in Find cmdlet.

**Comment by ravbhatnagar** [comment]
Exact name matches are now supported in the Find-AzureRmResource cmdlet through ResourceGroupNameEquals and ResourceNameEquals.

**Comment by johnwc** [comment]
This is still an issue, the cmdlet still throws this error. I don't believe this is by design, more it may be by design because of a bug. The documentation in example # 2 clearly shows that this should be a viable use.
[Get-AzureRmResource documentation](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/get-azurermresource?view=azurermps-6.5.0#examples)

**Comment by jfinnecy** [comment]
Agree, I cannot get any of the examples in the Get-AzureRmResource documentation to do anything but throw error. For example:

>> Get-AzureRmResource -ResourceType Microsoft.Compute/virtualMachines | ft 

Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.

I have entered example #6 from the documentation exactly. None of the other examples work, either. If this is by design, please fix the documentation and show us how we are supposed to query resources. Note, the base command without parameters works, and lists all resources.

**Comment by dapostoladeloitte** [comment]
I will second that one from johnwc

**Comment by MicahMcKittrick-MSFT** [comment]
@vivsriaus seems people are still having issues. Can you reopen and take a look?

**Comment by AuroraBrignola** [comment]
+1 for re-opening

**Comment by ravbhatnagar** [comment]
reopening, will investigate and get back. @Tiano2017 FYI.

**Comment by COMikaze** [comment]
I have same issue, got around it by using oDataQuery parameter.

**Comment by johnwc** [comment]
@COMikaze apricate the workaround, but this issue is about getting it fixed and not finding a work around.

**Comment by hamsome** [comment]
Yup, having the same problem when I use
Get-AzureRmResource -ResourceType Microsoft.Web/sites

Please fix.

**Comment by tr1al3x** [comment]
same..

**Comment by cohowap** [comment]
Shouldn't this be a bigger issue since Find-AzureRmResource is removed now?  I am not sure how this thread isn't blown up.  Getting resources in a resource group seems like a basic.

**Comment by theMickster** [comment]
Receiving this same error when attempting to find all SQL Azure Databases. 

Get-AzureRmResource -ResourceType 'Microsoft.Sql/servers/databases'

Running version 6.11.0 of the Azure PowerShell module.

**Comment by nirmalpavan** [comment]
Facing this error while executing in runbook.

Get-AzureRmKeyVault : Parameter set cannot be resolved using the specified named parameters.
At line:13 char:10
+ $value = Get-AzureRmKeyVault `
+          ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmKeyVault], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.KeyVault.GetAzureKeyVault

**Comment by taylorbindon** [comment]
I've started experiencing the same error that others have outlined. Using Find-AzureRmResource as a work around for the time being.
```
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRmResource -ResourceGroupName test | ft
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
```

**Comment by markwkjr** [comment]
Upgrading to the latest AzureRM module to the latest `6.13.1` version corrected this for me.

Until I figured that out, as a work-around I used the following. It may be a little slower depending on how many Resources you have but:
```Powershell
Get-AzureRmResource | Where-Object { $_.ResourceGroupName -eq "test" }
```

**Comment by marc-gmail-towersap** [comment]
weird, it used to work. now it doesn't.  Am trying to test around it using something like
$myrg = (get-azurermresource -name "somename").resourcegroupname 2>&1

and I want to evaluate $myrg so if I get that error message, to instead use find-azurermresource (which so far still works... so far...)
but I can't seem to get it to work.  That re-direct of stderr to stdout is simply not working, $myrg is null.

I tried installing various AzureRM modules, nothing seems to work, including the latest (6.13.1).  hence, this stupid hack that so far isn't working.  Does anyone know how to make that re-direct work so I can test it out?

**Comment by paulstroh** [comment]
Try using the Powershell cloud shell CLI from the Azure portal.  This
worked for me and saved me the hassle of dealing with different module
versions.

____________________________________

Paul Stroh

Sr. Systems Engineer - IT

Dycom Industries, Inc.

Tel: 561-799-3277 <561-799-3277>

paul.stroh@dycominc.com

This email, and any documents which may accompany it, contain information
which is intended for use only by the individual to whom it is addressed,
and may contain information that is privileged, confidential and/or exempt
from disclosure under applicable law. If the reader of this message is not
the intended recipient any review, disclosure, dissemination, distribution,
copying or other use of this message or its substance is strictly
prohibited.  If you have received this message in error, please contact me
immediately to arrange for return or destruction.  Thank you.


On Thu, Dec 20, 2018 at 6:40 PM marc-gmail-towersap <
notifications@github.com> wrote:

> weird, it used to work. now it doesn't. Am trying to test around it using
> something like
> $myrg = (get-azurermresource -name "somename").resourcegroupname 2>&1
>
> and I want to evaluate $myrg so if I get that error message, to instead
> use find-azurermresource (which so far still works... so far...)
> but I can't seem to get it to work. That re-direct of stderr to stdout is
> simply not working, $myrg is null.
>
> I tried installing various AzureRM modules, nothing seems to work,
> including the latest (6.13.1). hence, this stupid hack that so far isn't
> working. Does anyone know how to make that re-direct work so I can test it
> out?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Azure_azure-2Dpowershell_issues_2605-23issuecomment-2D449176682&d=DwMFaQ&c=Mgo4QHoKQyU6CPiMGzPHbA&r=xluCLDmyGsVuxvaqs-A8UcLFgvAOzq6c_JOSxbRb1-k&m=VrF-ijF4CXFooUQIfkfqu2R5cf6n02Mm_MdstDbe5Mo&s=_0Vo9scfQVLI3qOy7HDzfeLcF8xCIY5OVFGEDtiPbPA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AqMUQsgY0RczBXiKS3YRmu5s049mB4iXks5u7B-5FTgaJpZM4JLsxx&d=DwMFaQ&c=Mgo4QHoKQyU6CPiMGzPHbA&r=xluCLDmyGsVuxvaqs-A8UcLFgvAOzq6c_JOSxbRb1-k&m=VrF-ijF4CXFooUQIfkfqu2R5cf6n02Mm_MdstDbe5Mo&s=wrvIhRaBWwznO6rR4OdlBJlfemQrc3VglI8ZNPciVQI&e=>
> .
>

-- 


This email message, and any documents which may accompany it, contain

information which is intended for use only by the intended recipient(s), 
and
may contain information that is privileged and/or confidential. If you 
are not
the intended recipient of this message you are hereby notified that 
any review,
disclosure, dissemination, distribution, copy or other use of 
this message or
its attachments is strictly prohibited. If you have 
received this message in
error, please notify the sender by reply email, 
delete the email from your
computer and destroy all copies of the 
communication and any attachments.

**Comment by maddieclayton** [comment]
This is working in our most recent version of Az as well as the last released version of AzureRM.  If you are still seeing issues with Get-AzResource on Az (https://www.powershellgallery.com/packages/Az.Resources/1.0.0), please open a new bug.  Thanks all!

**Comment by rajatchakraborty91** [comment]
Any updates on this? I'm still getting an error with azurerm 6.7/6.13

**Comment by rthorn17** [comment]
@rajatchakraborty91   I know it is working within the AzureAZ modules.  Can you run the command with "-debug" and send me the response to see what is going on.  You can email me at rithorn@microsoft.com  if you don't want to post details here.  Thanks

**Comment by varleg** [comment]
Getting the error in runbook as of 12/19-19
