### ISSUE TITLE
[2.1.0] Azure module fails to install 

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#2916]
### Cmdlet(s)
Install-Module

### PowerShell Version
5.1.14393.103

### Module Version
Azure 2.1.0, PowerShellGet 1.0.0.1

### OS Version
10.0.14393.103

### Description
When I try to install Azure module on a clean machine, I get the following error:
```
PackageManagement\Install-Package : A command with name 'Get-AzureStorageContainerAcl' is already available on this
system. This module 'Azure' may override the existing commands. If you still want to install this module 'Azure', use
-AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1661 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], E
   xception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Packa
   geManagement.Cmdlets.InstallPackage
```

My system didn't have the `Get-AzureStorageContainerAcl` before I've tried to install Azure module. It came with Azure.Storage as Azure.Storage is a dependent module. I haven't experienced this behavior with previous versions of Azure.

WORKAROUND: Use `Install-Module Azure -AllowClobber`
### Script/Steps for Reproduction
`Install-Module azure -Verbose`

**Comment by markcowl** [comment]
@alexandair This is new behavior in version 5.1 preview of PowerShell, not anything that has changed in our modules - we had this same behavior as soon as 5.1 was released.

This is caused by 2 aliases (the storage aliases you mention) and 2 cmdlets, so although we could change the storage aliases, 2 cmdlets would still have to be renamed.

**Comment by rolandoldengarm** [comment]
@markcowl This is not a solution?! I'm following the o[fficial documentation ](https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/) and I get this error. As it's red, it's an error, and I think something is wrong.
This should be fixed in the Azure-Powershell module.

**Comment by akunaatrium** [comment]
This is indeed unacceptable that following official documentation some errors are expected for which workarounds are needed to actually reach to a successful installation. Definitely a defect that should be fixed.

**Comment by rikkus** [comment]
What's the workaround please?

**Comment by minhio** [comment]
use the -AllowClobber parameter

`Install-Module AzureRM -AllowClobber`

**Comment by jiimaho** [comment]
So is it safe to use `Install-Module AzureRM -AllowClobber`?

**Comment by turagittech** [comment]
This is still happening, surprised it's not yet fixed
PS C:\Windows\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  1480

**Comment by joshnoe** [comment]
How about at least adding the workaround to the README?
