### ISSUE TITLE
Set-AzureRmApiManagementPolicy : ValidationError: Resource was modified since last retrieval

### ISSUE THREAD

**Issue by TheDude72** [Azure/azure-powershell#3817]
### Cmdlet(s)
Set-AzureRmApiManagementPolicy

### PowerShell Version
3.7.0
### OS Version
Windows 10

### Description
When I try to call the Set-AzureRmApiManagementPolicy PowerShell commandlet to update a policy in Azure API Management, I get the following error:

Set-AzureRmApiManagementPolicy : ValidationError: Resource was modified since last retrieval.

This error only occurs when a policy already exists. If I delete the policy and re-run it, then it works fine. So, there's some strange issue with updating the policy once it's already there. I know that this SHOULD work since I'm able to get this running if I call into Login-AzureRmAccount ahead of time and login. Then the updating of an existing policy works. It seems to be related to the way I'm authenticating with the Api Management REST API. I'm using a certificate method of authenticating which is why I don't need to call Login-AzureRmAccount.

### Debug Output
Environment           : AzureCloud
Account               : b3b0d268-0d04-4b9a-9bd6-01d74a373f8c
TenantId              : 067e9632-ea4c-4ed9-9e6d-e294956e284b
SubscriptionId        : 13cac5cb-2ec6-48c6-9a90-5a776f6aed90
CurrentStorageAccount : 
Account      : b3b0d268-0d04-4b9a-9bd6-01d74a373f8c
Environment  : AzureCloud
Subscription : 13cac5cb-2ec6-48c6-9a90-5a776f6aed90
Tenant       : 067e9632-ea4c-4ed9-9e6d-e294956e284b
DEBUG: 7:21:20 PM - NewAzureApiManagementContext begin processing with 
ParameterSet '__AllParameterSets'.
DEBUG: 7:21:20 PM - using account id 'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c'...
DEBUG: 7:21:20 PM - NewAzureApiManagementContext end processing.
DEBUG: 7:21:20 PM - GetAzureApiManagementProduct begin processing with 
ParameterSet 'Get all producst'.
DEBUG: 7:21:20 PM - using account id 'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c'...
DEBUG: [Common.Authentication]: Authenticating using Account: 
'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c', environment: 'AzureCloud', tenant: 
'067e9632-ea4c-4ed9-9e6d-e294956e284b'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 
DEBUG: 4/21/2017 7:21:21 PM:  - TokenCache: Deserialized 1 items to token 
cache.
DEBUG: [Common.Authentication]: Authenticating using configuration values: 
Domain: '067e9632-ea4c-4ed9-9e6d-e294956e284b', Endpoint: 
'https://login.windows.net/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2',
 ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 
'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Renewing token using AppId: 
'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c', AdalConfiguration with ADDomain: 
'067e9632-ea4c-4ed9-9e6d-e294956e284b', AdEndpoint: 
'https://login.windows.net/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2',
 RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 
DEBUG: 4/21/2017 7:21:21 PM: 87eba6c6-2f66-4604-baa4-300da528bb93 - 
AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.windows.net/067e9632-ea4c-4ed9-9e6d-e294956e284b/
 Resource: https://management.core.windows.net/
 ClientId: b3b0d268-0d04-4b9a-9bd6-01d74a373f8c
 CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (1 
items)
 Authentication Target: Client
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 4/21/2017 7:21:21 PM: 87eba6c6-2f66-4604-baa4-300da528bb93 - TokenCache:
 Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 
DEBUG: 4/21/2017 7:21:21 PM: 87eba6c6-2f66-4604-baa4-300da528bb93 - TokenCache:
 An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 4/21/2017 7:21:21 PM: 87eba6c6-2f66-4604-baa4-300da528bb93 - TokenCache:
 59.9486932516667 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 
DEBUG: 4/21/2017 7:21:21 PM: 87eba6c6-2f66-4604-baa4-300da528bb93 - TokenCache:
 A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 
DEBUG: 4/21/2017 7:21:21 PM: 87eba6c6-2f66-4604-baa4-300da528bb93 - 
AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access
 token was retuned:
 Access Token Hash: Xz9j/v/qg4T7x7SPohQBTyHAyGG5j7pvpoN1ZbAjrkw=
 Refresh Token Hash: [No Refresh Token]
 Expiration Time: 4/21/2017 8:21:17 PM +00:00

 User Hash: null

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:21 PM:  - TokenCache: Serializing token cache with 1 

items.

DEBUG: [Common.Authentication]: Received token with LoginType 'OrgId', Tenant: 

'067e9632-ea4c-4ed9-9e6d-e294956e284b', UserId: 

'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c'

DEBUG: [Common.Authentication]: Checking token expiration, token expires 

'04/21/2017 20:21:17 +00:00' Comparing to '04/21/2017 19:21:21 +00:00' With 

threshold '00:05:00', calculated time until token expiry: '00:59:56.8590934'

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:

GET

Absolute Uri:

https://management.azure.com/subscriptions/13cac5cb-2ec6-48c6-9a90-5a776f6aed90

/resourceGroups/dev-ims-eus/providers/Microsoft.ApiManagement/service/DevImsApi

m/products?api-version=2014-02-14

Headers:

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:

OK

Headers:

Pragma                        : no-cache

Strict-Transport-Security     : max-age=31536000; includeSubDomains

x-ms-request-id               : 6a97fb9a-ca38-448d-b5b1-319ed6e76f05

x-ms-ratelimit-remaining-subscription-reads: 14966

x-ms-correlation-request-id   : 2ccd30e5-21b4-4ba6-b760-cdfc798d3f64

x-ms-routing-request-id       : 

EASTUS:20170421T192121Z:2ccd30e5-21b4-4ba6-b760-cdfc798d3f64

Cache-Control                 : no-cache

Date                          : Fri, 21 Apr 2017 19:21:21 GMT

Server                        : Microsoft-HTTPAPI/2.0

Body:

{

  "value": [

    {

      "id": "/products/54321",

      "name": "IMS-APIS",

      "description": "Description",

      "terms": "Free for all",

      "subscriptionRequired": true,

      "approvalRequired": false,

      "subscriptionsLimit": null,

      "state": "published"

    },

    {

      "id": "/products/58e3df86bb36090076060001",

      "name": "Starter",

      "description": "Subscribers will be able to run 5 calls/minute up to a 

maximum of 100 calls/week.",

      "terms": "",

      "subscriptionRequired": true,

      "approvalRequired": false,

      "subscriptionsLimit": 1,

      "state": "notPublished"

    },

    {

      "id": "/products/58e3df86bb36090076060002",

      "name": "Unlimited",

      "description": "Subscribers have completely unlimited access to the API. 

Administrator approval is required.",

      "terms": null,

      "subscriptionRequired": true,

      "approvalRequired": true,

      "subscriptionsLimit": 1,

      "state": "notPublished"

    }

  ],

  "count": 3,

  "nextLink": null

}

DEBUG: 7:21:21 PM - GetAzureApiManagementProduct end processing.

App Setting found: Policy.IMS-APIS

App Setting found: System.Collections.Generic.Dictionary`2[System.String,System.String][Policy.IMS-APIS]

App Setting found: IMS-APIS

Name of the product  +Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementProduct.Title

DEBUG: 7:21:21 PM - GetAzureApiManagementPolicy begin processing with 

ParameterSet 'Product level'.

DEBUG: 7:21:21 PM - using account id 'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c'...

DEBUG: [Common.Authentication]: Authenticating using Account: 

'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c', environment: 'AzureCloud', tenant: 

'067e9632-ea4c-4ed9-9e6d-e294956e284b'

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:21 PM:  - TokenCache: Deserialized 1 items to token 

cache.

DEBUG: [Common.Authentication]: Authenticating using configuration values: 

Domain: '067e9632-ea4c-4ed9-9e6d-e294956e284b', Endpoint: 

'https://login.windows.net/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2',

 ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 

'https://management.core.windows.net/', ValidateAuthrity: 'True'

DEBUG: [Common.Authentication]: Renewing token using AppId: 

'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c', AdalConfiguration with ADDomain: 

'067e9632-ea4c-4ed9-9e6d-e294956e284b', AdEndpoint: 

'https://login.windows.net/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2',

 RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:21 PM: 68ceab73-c97a-458f-a24f-aff9e61beabd - 

AcquireTokenHandlerBase: === Token Acquisition started:

 Authority: https://login.windows.net/067e9632-ea4c-4ed9-9e6d-e294956e284b/

 Resource: https://management.core.windows.net/

 ClientId: b3b0d268-0d04-4b9a-9bd6-01d74a373f8c

 CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (1 

items)

 Authentication Target: Client

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 

DEBUG: 4/21/2017 7:21:21 PM: 68ceab73-c97a-458f-a24f-aff9e61beabd - TokenCache:

 Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:21 PM: 68ceab73-c97a-458f-a24f-aff9e61beabd - TokenCache:

 An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 

DEBUG: 4/21/2017 7:21:21 PM: 68ceab73-c97a-458f-a24f-aff9e61beabd - TokenCache:

 59.938797465 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:21 PM: 68ceab73-c97a-458f-a24f-aff9e61beabd - TokenCache:

 A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:21 PM: 68ceab73-c97a-458f-a24f-aff9e61beabd - 

AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access

 token was retuned:

 Access Token Hash: Xz9j/v/qg4T7x7SPohQBTyHAyGG5j7pvpoN1ZbAjrkw=

 Refresh Token Hash: [No Refresh Token]

 Expiration Time: 4/21/2017 8:21:17 PM +00:00

 User Hash: null

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:21 PM:  - TokenCache: Serializing token cache with 1 

items.

DEBUG: [Common.Authentication]: Received token with LoginType 'OrgId', Tenant: 

'067e9632-ea4c-4ed9-9e6d-e294956e284b', UserId: 

'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c'

DEBUG: [Common.Authentication]: Checking token expiration, token expires 

'04/21/2017 20:21:17 +00:00' Comparing to '04/21/2017 19:21:21 +00:00' With 

threshold '00:05:00', calculated time until token expiry: '00:59:56.3122204'

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:

GET

Absolute Uri:

https://management.azure.com/subscriptions/13cac5cb-2ec6-48c6-9a90-5a776f6aed90

/resourceGroups/dev-ims-eus/providers/Microsoft.ApiManagement/service/DevImsApi

m/products/54321/policy?api-version=2014-02-14

Headers:

Accept                        : application/vnd.ms-azure-apim.policy+xml

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:

OK

Headers:

Pragma                        : no-cache

Strict-Transport-Security     : max-age=31536000; includeSubDomains

x-ms-request-id               : c9d757d4-1466-43dc-a6f4-3fca81da466a

x-ms-ratelimit-remaining-subscription-reads: 14975

x-ms-correlation-request-id   : 51b1db54-7c53-4a22-9d5a-b0109e18ceac

x-ms-routing-request-id       : 

EASTUS:20170421T192122Z:51b1db54-7c53-4a22-9d5a-b0109e18ceac

Cache-Control                 : no-cache

Date                          : Fri, 21 Apr 2017 19:21:22 GMT

ETag                          : "AAAAAAAADNU="

Server                        : Microsoft-HTTPAPI/2.0

Body:

<policies>

  <inbound>

    <base />

    <quota calls="10000" bandwidth="5000" renewal-period="86400" />

    <rate-limit-by-key calls="1000" renewal-period="60" 

increment-condition="@(context.Response.StatusCode == 200)" 

counter-key="@(context.Subscription.Id)" />

    <retry condition="@(context.Response.StatusCode == 500)" count="10" 

interval="3" max-interval="30" delta="5"></retry>

  </inbound>

  <backend>

    <base />

    

  </backend>

  <outbound>

    <base />

  </outbound>

  <on-error>

    

  </on-error>

</policies>

DEBUG: 7:21:22 PM - GetAzureApiManagementPolicy end processing.

DEBUG: 7:21:22 PM - SetAzureApiManagementPolicy begin processing with 

ParameterSet 'Product level'.

DEBUG: 7:21:22 PM - using account id 'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c'...

DEBUG: [Common.Authentication]: Authenticating using Account: 

'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c', environment: 'AzureCloud', tenant: 

'067e9632-ea4c-4ed9-9e6d-e294956e284b'

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:22 PM:  - TokenCache: Deserialized 1 items to token 

cache.

DEBUG: [Common.Authentication]: Authenticating using configuration values: 

Domain: '067e9632-ea4c-4ed9-9e6d-e294956e284b', Endpoint: 

'https://login.windows.net/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2',

 ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 

'https://management.core.windows.net/', ValidateAuthrity: 'True'

DEBUG: [Common.Authentication]: Renewing token using AppId: 

'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c', AdalConfiguration with ADDomain: 

'067e9632-ea4c-4ed9-9e6d-e294956e284b', AdEndpoint: 

'https://login.windows.net/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2',

 RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:22 PM: 8d20c825-f249-4bfc-9a8d-b261a5b560a2 - 

AcquireTokenHandlerBase: === Token Acquisition started:

 Authority: https://login.windows.net/067e9632-ea4c-4ed9-9e6d-e294956e284b/

 Resource: https://management.core.windows.net/

 ClientId: b3b0d268-0d04-4b9a-9bd6-01d74a373f8c

 CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (1 

items)

 Authentication Target: Client

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 

DEBUG: 4/21/2017 7:21:22 PM: 8d20c825-f249-4bfc-9a8d-b261a5b560a2 - TokenCache:

 Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:22 PM: 8d20c825-f249-4bfc-9a8d-b261a5b560a2 - TokenCache:

 An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 

DEBUG: 4/21/2017 7:21:22 PM: 8d20c825-f249-4bfc-9a8d-b261a5b560a2 - TokenCache:

 59.93098482 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:22 PM: 8d20c825-f249-4bfc-9a8d-b261a5b560a2 - TokenCache:

 A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:22 PM: 8d20c825-f249-4bfc-9a8d-b261a5b560a2 - 

AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access

 token was retuned:

 Access Token Hash: Xz9j/v/qg4T7x7SPohQBTyHAyGG5j7pvpoN1ZbAjrkw=

 Refresh Token Hash: [No Refresh Token]

 Expiration Time: 4/21/2017 8:21:17 PM +00:00

 User Hash: null

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory rmation: 2 : 

DEBUG: 4/21/2017 7:21:22 PM:  - TokenCache: Serializing token cache with 1 

items.

DEBUG: [Common.Authentication]: Received token with LoginType 'OrgId', Tenant: 

'067e9632-ea4c-4ed9-9e6d-e294956e284b', UserId: 

'b3b0d268-0d04-4b9a-9bd6-01d74a373f8c'

DEBUG: [Common.Authentication]: Checking token expiration, token expires 

'04/21/2017 20:21:17 +00:00' Comparing to '04/21/2017 19:21:22 +00:00' With 

threshold '00:05:00', calculated time until token expiry: '00:59:55.8277097'

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:

PUT

Absolute Uri:

https://management.azure.com/subscriptions/13cac5cb-2ec6-48c6-9a90-5a776f6aed90

/resourceGroups/dev-ims-eus/providers/Microsoft.ApiManagement/service/DevImsApi

m/products/54321/policy?api-version=2014-02-14

Headers:

Body:

<policies>

  <inbound>

    <base />

    <quota calls="10000" bandwidth="5000" renewal-period="86400" />

    <rate-limit-by-key calls="1000" renewal-period="60" 

increment-condition="@(context.Response.StatusCode == 200)" 

counter-key="@(context.Subscription.Id)" />

    <retry condition="@(context.Response.StatusCode == 500)" count="10" 

interval="3" max-interval="30" delta="5"></retry>

  </inbound>

  <backend>

    <base />

    

  </backend>

  <outbound>

    <base />

  </outbound>

  <on-error>

    

  </on-error>

</policies>

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:

BadRequest

Headers:

Pragma                        : no-cache

Strict-Transport-Security     : max-age=31536000; includeSubDomains

x-ms-request-id               : ab46ac49-fe5e-42a4-ba39-6777980e760f

x-ms-ratelimit-remaining-subscription-writes: 1199

x-ms-correlation-request-id   : b3762a17-9b6b-442b-a502-775f595f99b1

x-ms-routing-request-id       : 

EASTUS:20170421T192123Z:b3762a17-9b6b-442b-a502-775f595f99b1

Cache-Control                 : no-cache

Date                          : Fri, 21 Apr 2017 19:21:22 GMT

Server                        : Microsoft-HTTPAPI/2.0

Body:

{

  "error": {

    "code": "ValidationError",

    "message": "Resource was modified since last retrieval.",

    "details": null

  }

}

Set-AzureRmApiManagementPolicy : ValidationError: Resource was modified since 

last retrieval.

At D:\Octopus\Work\20170421192102-145\Script.ps1:31 char:33

+ ...             Set-AzureRmApiManagementPolicy -Context $apicontext -Prod ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + Category          : CloseError: (:) [Set-AzureRmApiManagementPolicy] 

   , CloudException

    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.SetAzureApiManagementPolicy

### Script/Steps for Reproduction
$policy=""
$ResourceGroupName = "dev-ims-eus"
$serviceName = "DevImsApim"

$apicontext = New-AzureRmApiManagementContext -ResourceGroupName $ResourceGroupName -ServiceName $serviceName

$product =  Get-AzureRmApiManagementProduct -Context $apicontext

$policyString = "<policies><inbound><base /><quota calls='10000' bandwidth='5000' renewal-period='86400' /><rate-limit-by-key calls='1000' renewal-period='60' increment-condition='@(context.Response.StatusCode == 200)' counter-key='@(context.Subscription.Id)'/><retry condition='@(context.Response.StatusCode == 500)' count='10' interval='3' max-interval='30' delta='5'></retry></inbound><backend><base /></backend><outbound><base /></outbound><on-error></on-error></policies>"

$parameter = "Policy.IMS-APIS"

$split = ($parameter.split('.'))
$name = $split[1]

write-host "App Setting found: $name"

foreach ($prod in $product) 
{
    Write-Host "Name of the product "+$prod.Title
    if($prod.Title -eq $name)
    {
        $poliyccheck = Get-AzureRmApiManagementPolicy -Context $apicontext -ProductId $prod.ProductId
        if (-Not ([string]$poliyccheck -match 'Bentley.STS.RegistrationService'))
        {
        $policy=$policyString
        Set-AzureRmApiManagementPolicy -Context $apicontext -ProductId $prod.ProductId -Policy  $policy
        }          
    }
}

**Comment by solankisamir** [comment]
The issue is due to the Headers in the request missing **If-Match** Header.  It should be set to `*`
`Headers:
If-Match                      : *`

$PSVersionTable
`PSVersion                      5.1.15063.138`
`BuildVersion                   10.0.15063.138`
`CLRVersion                     4.0.30319.42000`
`WSManStackVersion              3.0`
`PSRemotingProtocolVersion      2.3`
`SerializationVersion           1.1.0.1`

Get-Module -Name AzureRm.ApiManagement
`Manifest   3.4.0      AzureRM.ApiManagement

Can you provide the version of ApiManagement module you are running? I could not reproduce the problem on above version. Latest version is 3.7.0

**Comment by TheDude72** [comment]
I believe it's version 1.0.1.  Here's all of the info I get back when I run that "Get-Module" commandlet:

**_Environment           : AzureCloud
Account               : b3b0d268-0d04-4b9a-9bd6-01d74a373f8c
TenantId              : 067e9632-ea4c-4ed9-9e6d-e294956e284b
SubscriptionId        : 13cac5cb-2ec6-48c6-9a90-5a776f6aed90
CurrentStorageAccount : 
Account      : b3b0d268-0d04-4b9a-9bd6-01d74a373f8c

Environment  : AzureCloud
Subscription : 13cac5cb-2ec6-48c6-9a90-5a776f6aed90
Tenant       : 067e9632-ea4c-4ed9-9e6d-e294956e284b
Name              : AzureRM.ApiManagement
Path              : D:\Octopus\Calamari\Azure\3.3.1\AzurePowershell\ResourceMan
                    ager\AzureResourceManager\AzureRM.ApiManagement\AzureRM.Api
                    Management.psd1
Description       : Microsoft Azure PowerShell - Api Management service 
                    cmdlets for Azure Resource Manager
Guid              : f875725d-8ce4-423f-a6af-ea880bc63f13
Version           : 1.0.1
ModuleBase        : D:\Octopus\Calamari\Azure\3.3.1\AzurePowershell\ResourceMan
                    ager\AzureResourceManager\AzureRM.ApiManagement
ModuleType        : Manifest_**

**Comment by TheDude72** [comment]
I'm running this through the PowerShell that comes with Octopus, btw.

**Comment by TheDude72** [comment]
Did something change on Microsoft's side today?  This was actually working for the past several weeks.  It just stopped working today.  Which is why I'm beginning to wonder if some validation rule was changed on the APIM REST API side of things.

**Comment by solankisamir** [comment]
@TheDude72 There was a bug in the Version of the Cmdlet you are using, which was fixed in https://github.com/Azure/azure-powershell/commit/871c779bb6c9088f15b210b1dfe0a08151a0a7c6#diff-72bf21c9cbd6229758d241b15cb6a595R1042

Suggest you upgrade the AzureRm.ApiManagement module to 2.2.0 and let me know if you can still reproduce it.

**Comment by TheDude72** [comment]
@solankisamir Actually, as it turns out, Octopus (the platform I'm using to execute PowerShell commandlets) is using the latest version of AzureRM.ApiManagement (version 3.5.0).  Could there be a bug introduced with the latest version?:

_**Name              : AzureRM.ApiManagement
Path              : C:\Program Files\WindowsPowerShell\Modules\AzureRM.ApiManag
                    ement\3.5.0\AzureRM.ApiManagement.psd1
Description       : Microsoft Azure PowerShell - Api Management service 
                    cmdlets for Azure Resource Manager
Guid              : f875725d-8ce4-423f-a6af-ea880bc63f13
Version           : 3.5.0
ModuleBase        : C:\Program 
                    Files\WindowsPowerShell\Modules\AzureRM.ApiManagement\3.5.0**_

**Comment by solankisamir** [comment]
@TheDude72 we tried to reproduce it on latest PowerShell version, but there is no issue on the service side.
 
You are using a very old version of the Module. From the Debug logs, I can see that you are using 
`api-version=2014-02-14`
`https://management.azure.com/subscriptions/13cac5cb-2ec6-48c6-9a90-5a776f6aed90/resourceGroups/dev-ims-eus/providers/Microsoft.ApiManagement/service/DevImsApim/products/54321/policy?api-version=2014-02-14`, 

we migrated away from that version in 2015.

As mentioned this bug was fixed in https://github.com/Azure/azure-powershell/commit/871c779bb6c9088f15b210b1dfe0a08151a0a7c6#diff-72bf21c9cbd6229758d241b15cb6a595R1042

**Comment by solankisamir** [comment]
If you were using the 3.5.0 cmdlet, then the api-version would have been `2016-10-10`

**Comment by TheDude72** [comment]
We're using whatever version is being hosted on the Azure VM.  Octopus deployment runs on top of the Azure VM.  When I run "Get-Module", it shows 3.5

But I see that your are correct about the debug information.  Whatever version it is, it's translating into REST api call with the older api version.  I think I should probably just scrap the idea of using a PowerShell commandlet and call the REST API directly.  Less headaches.

**Comment by solankisamir** [comment]
@TheDude72 can you point me to their documentation. If its Azure, maybe I can get in touch with them and see where the issue is.

**Comment by TheDude72** [comment]
I can point you to the forum where an Octopus support member explained to me that Octopus always uses the latest available version of PowerShell in the VM.  As for the modules, he says they come bundled with Octopus.  Although, that still doesn't explain why it was coming back as version 3.5 when I ran Get-Module on it:

http://help.octopusdeploy.com/discussions/questions/11450-how-is-powershell-and-its-modules-updated-in-octopus

**Comment by solankisamir** [comment]
I have opened an issue http://help.octopusdeploy.com/discussions/problems/54000-using-old-cmdlets-for-azurermapimanagement

**Comment by TheDude72** [comment]
I wonder if the "Get-Module" commandlet I was running in Octopus was actually pulling the version that came with the VM (which is 3.5).  But then when Octopus executes, it uses the older (hidden) version that comes bundled with it.  Just a thought...
