### ISSUE TITLE
Get-AzureRmResource -ResourceGroupName "aa" throws "Parameter set cannot be resolved" exception

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-powershell#4035]
### Cmdlet(s)
Get-AzureRmResource
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
latest available. 

### Module Version
AzureRM.Resources 

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
Windows 10

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
```
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRmResource -ResourceGroupName "aa"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets
   .Implementation.GetAzureResourceCmdlet
```

### Script/Steps for Reproduction
Get-AzureRmResource -ResourceGroupName "aa"

**Comment by KirkMunro** [comment]
Any movement on this issue? In the docs Example 2 (Get-AzureRmResource -ResourceGroupName ContosoRG01) fails because the parameter sets are not defined correctly. There should be no ambiguity when using this command to enumerate all resources in a resource group, and this is such a basic task that it really should be working. The alternative is ugly too: get all resources in all resource groups and do client-side filtering with Where-Object. Yuck. Please get this fixed and pushed into an AzureRM release.

**Comment by cormacpayne** [comment]
This will be resolved in PR https://github.com/Azure/azure-powershell/pull/6008

**Comment by cormacpayne** [comment]
The fix for this should be available on May 7th in version 6.0.0 of `AzureRM` (version 6.0.0 of `AzureRM.Resources`). Please re-open this issue if the problem persists.

**Comment by sg84** [comment]
Hi, this issue still exists in 6.0.1. 

Get-AzureRmResource -ResourceGroupName rg3
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRmResource -ResourceGroupName rg3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

**Comment by virtualam** [comment]
I'm using AzureRM 6.13.1 and still get this issue.

**Comment by cormacpayne** [comment]
@virtualam what's the full command that you're running that receives this error? Also, would you mind providing the list of modules that you have installed on your machine by running `Get-Module -ListAvailable`?
