### ISSUE TITLE
AzureRm.Netcore Login-AzureRmAccount not working on Mac and Linux with Service Principal 

### ISSUE THREAD

**Issue by scgbear** [Azure/azure-powershell#4476]
### Cmdlet(s)
Login-AzureRmAccount

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
6.0.0-beta

### Module Version
0.9.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
Team is having issues executing the Login-AzureRmAccount cmdlet using a service principal from Mac and Linux boxes. The same script (with the same password, tenant id & username) run from a Windows 10 machine works fine. The Login-AzureRmAccount cmdlet works on the linux and mac boxes when executing the cmdlet without any parameters passed in and the user logs in manually. It's using the service principal that is having issues.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

DEBUG: 1:26:42 PM - AddAzureRMAccountCommand begin processing with ParameterSet 'ServicePrincipalWithSubscriptionId'.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'XXXXXXXXXXXXXXXXXX', Endpoint: 'https://login.microsoftonline.com/', ClientId: 'XXXXXXXXXXXXXXXXX', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
Login-AzureRmAccount : AADSTS50001: The application named https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXXX/ was not found in the tenant
named XXXXXXXXXXXXXXXXXX.  This can happen if the application has not been installed by the administrator of the tenant or consented to by
any user in the tenant.  You might have sent your authentication request to the wrong tenant.
Trace ID: 070ab52b-0a52-4bfd-8951-d160c3531b00
Correlation ID: 10368aee-0a64-4a5b-af11-22116e570920
Timestamp: 2017-08-15 20:26:44Z
At /XXXXXXXX/AzureResources/loginprin.ps1:13 char:1
+ Login-AzureRmAccount -Credential $Credentials -ServicePrincipal -Tena ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AdalServiceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

DEBUG: 1:26:43 PM - AddAzureRMAccountCommand end processing.
DEBUG: 1:26:43 PM - AddAzureRMAccountCommand end processing.

### Script/Steps for Reproduction
$PlainPassword = "XXXXXXXXXXXXXXXXXXXXXXXXXX"

$tenantID = "XXXXXXXXXXXXXXXXXXXXXX"

$UserName = "XXXXXXXXXXXXXXXXXXXXX"

$SecurePassword = $PlainPassword | ConvertTo-SecureString -AsPlainText -Force

$Credentials = New-Object System.Management.Automation.PSCredential -ArgumentList $UserName, $SecurePassword

Login-AzureRmAccount -Credential $Credentials -ServicePrincipal -TenantId $tenantID

**Comment by mrvladis** [comment]
Have exactly the same issue.

**Comment by dimitertodorov** [comment]
Same issue on OSX.

Tried with several combinations. Succeeds on Windows.

```
Trace ID: 1546ccf2-949b-400b-8a0e-3bd7142f1400
Correlation ID: 85fb2d48-d7b6-4f79-bd10-ba0d77eb4b22
Timestamp: 2017-08-25 17:23:16Z
```

**Comment by twsouthwick** [comment]
This actually does fail on Windows when running Powershell 6.0 using the AzureRM.Netcore module with the same error that I see on Linux. If you run on Powershell 5.0 using the AzureRM module, it succeeds.

**Comment by twsouthwick** [comment]
I tried cloning the project to see if it would be a trivial fix, but can't seem to get anything to compile. @markcowl do you have ideas (you're assigned to what seems a similar issue)? It fails to restore a ton of the packages. I'm using VS 2017 15.3.3, on the `preview` branch.

**Comment by TechnologyAnimal** [comment]
I am getting the same problem on OSX.  Running the cmdlet with debugging mode enabled, I noticed something interesting... it seems that it's trying to authenticate with an unknown client id?

DEBUG: 9:32:45 PM - AddAzureRMAccountCommand begin processing with ParameterSet 'ServicePrincipalWithSubscriptionId'.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'CorrectOmittdName', Endpoint: 'https://login.microsoftonline.com/', **ClientId: '1950a258-227b-4e31-a9cf-717495945fc2'**, ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'

**Comment by 4c74356b41** [comment]
any news on this one? this is about 2 months old :(

**Comment by sorenhansendk** [comment]
I have the same problem in a Docker container hosted in **Ubuntu 16.04.3** (Xenial) and with version **0.9.1 of AzureRM.NetCore** Powershell.

Any news about this?

**Comment by 4c74356b41** [comment]
@sorenhansendk its not like its related to docker. its a problem with Azure Powershell, you cannot auth silently to it, only manually. which is a total roadblock.

**Comment by twitchax** [comment]
The issue was identified, and I have made the fix as part of my Netcore work.

The issue is fixed by [this](https://github.com/twitchax/azure-powershell/blob/bf26f13b89f1f6473ac43aabd19b9e46ef89c10a/src/Common/Commands.Common.Authentication/Authentication/ServicePrincipalTokenProvider.cs#L83) change in [this commit](https://github.com/twitchax/azure-powershell/commit/bf26f13b89f1f6473ac43aabd19b9e46ef89c10a).

These changes also happen to include fixes that @cormacpayne previously submitted which address AutoMapper issues.

Finally, it would be great if others could verify.  My travis build is [here](https://travis-ci.org/twitchax/azure-powershell/builds/292496809), and it yielded the following docker image.

```bash
docker run -it --rm twitchax/azure-powershell-core:bf26f13b89f1f6473ac43aabd19b9e46ef89c10a
```

**Comment by 4c74356b41** [comment]
okay, I can verify that its working in the container. any chance we can get the binaries to integrate into our ci\cd?

**Comment by twitchax** [comment]
We likely won't ship new Netcore cmdlets until November 8; however, you can pull the fixed binaries out of the docker image, if you'd like.  They are in `/azure-powershell`.

**Comment by 4c74356b41** [comment]
Hey, thanks for the heads up. Just a side question. Did you already ship the auth changes i saw previewed? Like the starting as job or context persistence? If yes, will they be part of the netcore reléase? Is there any docs covering those? I couldn’t find anything (maybe its just me).

Thanks!

-------------------------- 
Thanks in advance! || ¡Gracias de antemano!

Gleb Boushev,
Azure MVP.

De: Aaron Roney
Enviado: viernes, 27 de octubre de 2017 0:04
Para: Azure/azure-powershell
CC: 4c74356b41; Manual
Asunto: Re: [Azure/azure-powershell] AzureRm.Netcore Login-AzureRmAccount notworking on Mac and Linux with Service Principal (#4476)

We likely won't ship new Netcore cmdlets until November 8; however, you can pull the fixed binaries out of the docker image, if you'd like. They are in /azure-powershell.

**Comment by twitchax** [comment]
Yep, the context persistence and job improvements were in 4.4.1 (a few weeks ago).  The docs on that are [here](https://docs.microsoft.com/en-us/powershell/azure/using-experimental-modules).

This _should_ be part of the November release for Netcore, and we will be making more of an effort to update the Netcore bits in a timely manner; however, the Netcore cmdlets are still officially in _preview_.

**Comment by 4c74356b41** [comment]
sorry, somehow missed that. keep up the great work!

**Comment by markcowl** [comment]
This should be fiuxed in this PR: https://github.com/Azure/azure-powershell/pull/4879

**Comment by Koalra** [comment]
This problem was solved? AzureRM.NetCore 0.9.1 has same problem to me.. I installed at Nov 17..

**Comment by twitchax** [comment]
@Koalra, these changes have not been released yet.

You can get a docker version of the latest right now here.

```bash
docker run -it --rm twitchax/azure-powershell-core:netcore
```

**Comment by 4c74356b41** [comment]
@twitchax any eta? ;) i thought you said November 8 previously ;)

**Comment by twitchax** [comment]
I did. :(

We are hoping by mid next week.

**Comment by mrvladis** [comment]
Any updates? It is almost December ;)

**Comment by markcowl** [comment]
Fix checked in.

**Comment by stuartleeks** [comment]
Is the fix released yet? It looks like there has been a recent AzureRM release, but I can't see one for AzureRM.NetCore :-(

**Comment by Walter-Shui** [comment]
I also meet the same error log.

```
Login-AzureRmAccount : AADSTS50001: The application named https://login.microsoftonline.com/*****/ was not found in the tenant named ********.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
Trace ID: b4ad5639-6c6a-457e-8f0c-f24f27ce0d00
Correlation ID: 68b9da5a-1361-4043-b930-aca9ed9065a5
```
I use the latest Power Shell on Linux according to the [link ](https://docs.microsoft.com/en-us/powershell/azure/install-azurermps-maclinux?view=azurermps-5.1.1).

How do I solve this?

**Comment by 4c74356b41** [comment]
I can confirm that service principal auth was fixed long time ago.

**Comment by stuartleeks** [comment]
@markcowl - is this fix included in a release for PSCore? The latest PSCore version of the module I can see is 0.9.1

**Comment by Know1** [comment]
Still doesn't look fixed on my systems
```
PS /tmp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018
Platform                       Unix
```

```
PS /tmp> Add-AzureRmAccount -Credential $cred -ServicePrincipal –TenantId $tenantId                                                                                                                                             Add-AzureRmAccount : AADSTS50001: The application named https://login.microsoftonline.com/OURTENANTID/ was not found in the tenant named OURTENANTID.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
Trace ID: 1ef870f9-dba3-4233-b4c9-4efd00c81200
Correlation ID: e8556a67-d4be-40c8-bfff-1e62434afc0a
Timestamp: 2018-02-01 06:59:10Z
At line:1 char:1
+ Add-AzureRmAccount -Credential $cred -ServicePrincipal –TenantId $ten ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AdalServiceException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand
```

variables omitted for security but the same script cut and pasted into windows works correctly.

```
Add-AzureRmAccount -Credential $cred -ServicePrincipal –TenantId $tenantId

Account          : APPID@COMPANY.onmicrosoft.com
SubscriptionName : OURSUBSCRIPTIONNAME
SubscriptionId   : SUBSCRIPTIONID
TenantId         : TENANTID
Environment      : AzureCloud
```

**Comment by 4c74356b41** [comment]
use this docker image, it will work:  
docker run -it --rm twitchax/azure-powershell-core:netcore

**Comment by Know1** [comment]
And if we don;t use docker?

**Comment by 4c74356b41** [comment]
you could rip the binaries out of the container ;) in case they are not released yet :))

**Comment by 4c74356b41** [comment]
@twitchax hey, latest AzureRm.Netcore reléase was 2017-07-28 :) can you shed some light on when you are going to reléase something with this problema fixed aka working for scripting on Linux? 

Thanks :)

**Comment by cormacpayne** [comment]
AzureRM.Netcore 0.10.0 has been released and can be found here: https://github.com/Azure/azure-powershell/releases/tag/v0.10.0-nc-February2018

**Comment by 4c74356b41** [comment]
but the freaking user login doesnt work ...

**Comment by twitchax** [comment]
Of which scenario are you speaking?

**Comment by Know1** [comment]
Seems to be working now for me

`
$ rm -rf /usr/local/share/powershell/Modules/AzureRM.Profile.Netcore/0.9.1/
$ pwsh

PS /tmp> Install-Module AzureRM.Profile.Netcore
PS /tmp> get-module AzureRM.Profile.Netcore -list | Select-Object Name,Version,Path
Name                    Version Path
----                    ------- ----
AzureRM.Profile.Netcore 0.10.0  /usr/local/share/powershell/Modules/AzureRM.Profile.Netcore/0.10.0/AzureRM.Profile.Netcore.psd1

PS /tmp> $tenantId = 'XXXXXXXXXXXXX'
PS /tmp> $user = "XXXXXXXXXXXXXXXX@company.onmicrosoft.com"
PS /tmp> $pass = ConvertTo-SecureString "XXXXXXXXXXXX" -AsPlainText –Force
PS /tmp> $cred = New-Object -TypeName pscredential –ArgumentList $user, $pass
PS /tmp> Add-AzureRmAccount -Credential $cred -ServicePrincipal –TenantId $tenantId

Account          : XXXXXXX@company.onmicrosoft.com
SubscriptionName : XXXXX Prod
SubscriptionId   : XXXXXXXX
TenantId         : XXXXXX
Environment      : AzureCloud
`

**Comment by 4c74356b41** [comment]
@twitchax talking about regular AD user login :(

**Comment by djmoore711** [comment]
I know this is a very old thread. I just installed PowerShell Core on my Mac via Brew and when I install the AzureRM module, I also cannot authenticate to Azure.

This is the error I receive:

Login-AzureRmAccount : The term 'Login-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.         Check the spelling of the name, or if a path was included, verify that the path is correct and try again.                                             At line:1 char:1                                                                                                                                      + Login-AzureRmAccount                                                                                                                                
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Login-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by cormacpayne** [comment]
@djmoore711 did you install the `AzureRM` or `AzureRM.Netcore` module? The `AzureRM` module is meant for desktop (PowerShell 5 / 5.1) and `AzureRM.Netcore` is meant for .NET Core (PowerShell 6). In the upcoming months we will be releasing an `Az` module that will work on both of these platforms so separate modules won't be needed.

**Comment by djmoore711** [comment]
I installed `AzureRM`, based on some older training modules made in a Windows environment. I just found the documentation on using `AzureRM.Netcore`. I am working on removing `AzureRM` and installing the `AzureRM.Netcore` edition. Thanks for the quick reply!
