### ISSUE TITLE
Get-AzureStorageContainer returns HTTP 403 when using SAS-Token instead of StorageKey

### ISSUE THREAD

**Issue by karlti** [Azure/azure-powershell#5053]
### PowerShell Version
5.1.15063.726

### Module Version
Azure.Storage, current version

### OS Version
10.0.15063.726

### Description
When calling `"Get-AzureStorageContainer"` with a `StorageContext` that has been created with a SAS Token, the call always fails with an Error: 

***"The remote server returned an error: (403) Forbidden. HTTP Status Code: 403 - HTTP Error Message: Server  failed to authenticate the request."***

when drilling into, it looks like the script queries the ACLs of the container and this cannot succeed with a SAS.

When I directly call into the "List Container" REST API, with a SAS-Token like this:

` Invoke-RestMethod -Method Get -Uri "https://<myAcc>.blob.core.windows.net/?sv=2017-04-17&ss=bfqt&srt=sco&sp=rwdlacup&se=2017-11-30T20:03:25Z&st=2017-11-127T12:03:25Z&spr=https&sig=tf1Fg0jGXzp7xSv4b%2BbzUsXXXXXXXXX%3D&comp=list"`

it succeeds.

Please either change the script to work with SAS Tokens or adjust the CmdLet Documentation.
Thank you.

with kind regards,
Karl Tietze

### Debug Output
*PS C:\windows\system32> Get-AzureStorageContainer -Context $context -Name test-cont-001
DEBUG: 15:03:38 - Init Operation Context for 'GetAzureStorageContainerCommand' with client request id  Azure-Storage-PowerShell-2eb24846-2cad-4a66-b90d-e4d100138d06. If you want to g
et more details, please add "-Debug" to your command.
DEBUG: 15:03:38 - GetAzureStorageContainerCommand begin processing with ParameterSet 'ContainerName'.
DEBUG: 15:03:38 - Use storage account '[SasToken]' from storage context.
DEBUG: 15:03:38 - Start 1th remote call, method: HEAD, destination: https://<myAccount>.blob.core.windows.net/test-cont-001?sv=2017-04-17&ss=bfqt&srt=sco&sp=rwdlacup&se=2017-12-10T23:01
:20Z&st=2017-11-30T15:01:20Z&spr=https&sig=KfdpXXXXXXXXXX2Bo0%3D&api-version=2017-04-17&restype=container.
DEBUG: 15:03:38 - Finish remote call for https://<myAccount>.blob.core.windows.net/test-cont-001?sv=2017-04-17&ss=bfqt&srt=sco&sp=rwdlacup&se=2017-12-10T23:01:20Z&st=2017-11-30T15:01:20
Z&spr=https&sig=KfdpXXXXXXXXXXBo0%3D&api-version=2017-04-17&restype=container with status code 403(Forbidden) and service request id 645140c0-001e-00ad-24
e4-694bff000000. Elapsed time 240,74 ms.
Get-AzureStorageContainer : The remote server returned an error: (403) Forbidden. HTTP Status Code: 403 - HTTP Error Message: Server failed to authenticate the request. Make sure 
the value of Authorization header is formed correctly including the signature.
At line:1 char:1
+ Get-AzureStorageContainer -Context $context -Name test-cont-001
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureStorageContainer], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageContainerCommand
 
DEBUG: 15:03:38 - GetAzureStorageContainerCommand end processing, Start 1 remote calls. Finish 1 remote calls. Elapsed time 435,89 ms. Client operation id: Azure-Storage-PowerShell-2
eb24846-2cad-4a66-b90d-e4d100138d06.
DEBUG: 15:03:38 - GetAzureStorageContainerCommand end processing.*

### Script/Steps for Reproduction
1: Create SAS Token in Azure Portal.

2: Create Context (here $sas01):
`$context = New-AzureStorageContext -StorageAccountName <myAccount>  -SasToken $sas01
$container = Get-AzureStorageContainer -Context $context -Name test-cont-001`

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment]
@karlti 
Thanks for reporting the issue!
Actually, this is a known issue. Get-AzureStorageContainer will also get container ACL, which need Account Key. 
We have already track the bug and will consider the fixing depends on our bandwidth and priority.

And I agree, we should doc it. 
I will add the account key requirement to the help doc in recent build.

**Comment by karlti** [comment]
Thank you :)

**Comment by zhiweiv** [comment]
Hi @blueww,  this thread was marked as closed, is it fixed? I can't get my job done becasue I only have sas token from our IT.

Where can I trace the fix status? Is there a workaround?

Thanks

**Comment by blueww** [comment]
This is closed since we have doc the SAS requirement in help.
I will consider to fix it in  a future release.

**Comment by zhiweiv** [comment]
Got it,

Thanks

**Comment by blueww** [comment]
This should has been fixed from Azure PowerShell release 5.4.0.

**Comment by tanmaysingh2257** [comment]
@blueww  - This does not seems to be fixed, I was already using 5.4.1 and have updated it to 5.5.0 but still I am getting the same error. See below:

```
C:\Dev Machine\Azure Storage> (Get-Module -ListAvailable | Where-Object{ $_.Name -eq 'AzureRM' }) `
| Select Version, Name, Author, PowerShellVersion; 

Version Name    Author                PowerShellVersion
------- ----    ------                -----------------
5.5.0   AzureRM Microsoft Corporation 3.0              
5.4.1   AzureRM Microsoft Corporation 3.0              

C:\Dev Machine\Azure Storage> $context=New-AzureStorageContext -StorageAccountName "111222test" -SasToken "MY SAS TOKEN"
$context | Get-AzureStorageblob -Container "111222test"
Get-AzureStorageblob : The remote server returned an error: (403) Forbidden. HTTP Status Code: 403 - HTTP Error Message: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
At line:2 char:12
+ $context | Get-AzureStorageblob -Container "111222test"
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureStorageBlob], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand
```

![image](https://user-images.githubusercontent.com/37352744/37375826-dae36cf4-26f7-11e8-8c5c-5dd4ab3010dd.png)

**Comment by blueww** [comment]
@tanmaysingh2257 
For list containers of a Storage account, server request the SAS token must be an Account SAS, but can't be a container/blob SAS. And the SAS token need at least: -Service Blob -ResourceType Service -Permission l (list).

Following Powershell cmdlets works on 5.5.0, to create an account SAS and list container with it., let me know if you have any problem to use it.

```
$sas = New-AzureStorageAccountSASToken -Service Blob -ResourceType Service -Permission l -Context $ctx
$ctxsas = New-AzureStorageContext -StorageAccountName $ctx.StorageAccountName -SasToken $sas
Get-AzureStorageContainer -Context $ctxsas
```

**Comment by EthanEiter** [comment]
@blueww Even after updating to version 5.5.0, I am still getting a 403 response using an SAS. Could it still be broken?
![image](https://user-images.githubusercontent.com/10080179/37780231-8f600e80-2dab-11e8-9065-d27b96b1201c.png)

**Comment by blueww** [comment]
@EthanEiter 

As my before reply in this issue, please check how the sas is created. 
Since list containers is an account wide operation (no matter you just get one account or list all accounts), you must run it with account sas instead of container sas, and the account sas needs at least: -Service Blob -ResourceType Service -Permission l (list).

You can see sample for how to create such a sas in my before reply.

**Comment by EthanEiter** [comment]
@blueww I just created an SAS with the permissions shown in this photo:
![image](https://user-images.githubusercontent.com/10080179/37838292-c64dd30e-2e74-11e8-829f-b7f44d512c15.png)

I still receive a 403 error:
![image](https://user-images.githubusercontent.com/10080179/37838383-fa60cec6-2e74-11e8-8cf8-0c39dd1259f7.png)

**Comment by blueww** [comment]
@EthanEiter 

Would you please share the SAS string (hide sig, since it's credential), then I can check if the SAS is OK? And please make sure the SAS is created with same storage account with the storage account name set in New-AzureStorageContext.
And please add -debug to the failed cmdlets, and show the result, then we can see the server request ID and do more investigation.

**Comment by EthanEiter** [comment]
Ok, I created an SAS with the following credentials (all of them) on the same account that I am using in New-AzureStorageContext
![image](https://user-images.githubusercontent.com/10080179/38039807-e8e0b98a-3262-11e8-983c-fdf9f3ae2d1e.png)

This is the resulting SAS (with sig scrubbed)

> ?sv=2017-04-17&ss=bfqt&srt=sco&sp=rwdlacup&st=2018-03-23T08%3A15%3A00Z&se=2018-03-30T08%3A15%3A00Z&sig=xxxx

Again, here is the result:
![image](https://user-images.githubusercontent.com/10080179/38040090-9e9bc4e0-3263-11e8-8a68-35697138326d.png)

thanks

**Comment by blueww** [comment]
@EthanEiter 
The same sceanrio works well in my test. I also created a  SAS with storage explorer.
`?sv=2017-04-17&ss=bfqt&srt=sco&sp=rwdl&st=2018-03-24T09%3A54%3A00Z&se=2018-03-30T09%3A54%3A00Z&sig=***`

Then it works well in Get-AzureStorageContianer:
![image](https://user-images.githubusercontent.com/6926193/38066556-1502e7b2-333b-11e8-926e-f91a152b1bce.png)

Please make sure:
1. Can the SAS be used to run other storage request on same storage account? Like create container?
2. What's the Azure.Storage Module version? (Get it by run "Get-Module") On my machine which installed Azure Powershell 5.5.0, the version is 4.2.0
3. Please add "-debug" to Get-azureStorageContainer cmdlets, then show the result. Then we can see the request ID and do more investigation. (in the picture from you, the "-debug" is not added.)

**Comment by EthanEiter** [comment]
Sorry, I completely forgot about the -debug param
![image](https://user-images.githubusercontent.com/10080179/38098170-296317b8-332c-11e8-8165-c228a735598c.png)

1. No, I cannot make a new container either
![image](https://user-images.githubusercontent.com/10080179/38098517-222ae5ec-332d-11e8-951e-1e9df13af212.png)
2. The installed version of Azure.Storage is 4.2.0
![image](https://user-images.githubusercontent.com/10080179/38098560-410fa5c4-332d-11e8-88cd-649ad3e83500.png)

**Comment by blueww** [comment]
@EthanEiter ,  Since the SAS not work in other scenarios, it looks like the SAS is not valid. Would you please help to verify if the SAS works in other storage tools like Storage Explorer?

Besides that, you hide the server request ID in the output, so I can't find the server log to do more investigation. Would you please don't hide the server request ID in the output. I only need output on Get-AzureStorageContainer with -debug. 
Besides that, If you can show the command to create the storageContext and list container without hide the storage account name and container name (only hide the sig in SAS as it's credential), it will help more on the investigation.

**Comment by EthanEiter** [comment]
@blueww 

Thank you so much for your help, that was the issue. Rather strange that the SAS has to be generated on the machine that you are going to use it on...
