### ISSUE TITLE
Keyvault unresponsive for long time after using New-AzureRMKeyvault 

### ISSUE THREAD

**Issue by pixelicous** [Azure/azure-powershell#5326]
### Cmdlet(s)
New-AzureRMKeyvault

### PowerShell Version
5.1.15063.674 

### Module Version
4.0.1      AzureRM.KeyVault 

### OS Version
10.0.15063.674

### Description
When creating a keyvault in azure, the Azure DNS doesn't get replicated fast enough. Executions fail to create secrets afterwards. When creating our own script we make all sorts of mechanisms to wait on the keyvault to be accessible, but when other IAC tools such as terraform try to also create secrets, they fail, the keyvault can't be found yet and it fails.

This isn't terraform issue but an azure one, i see the same error when i try to create the new-keyvault myself. 
This cmdlet, or the Azure API in general, shouldn't return a success or an object unless the keyvault has been successfully replicated across Azure. 

We even tried to generate an Iaas VM in Azure and replicate the problem with a server that resides on Azure's platform, same problem, the replication is juts not fast enough for many tools to work with, such as terraform, they even added whole whopping two minutes to wait for keyvault to propogate and in many instances that isn't enough.

This is causing numerous fails and it doesn't happen everytime, the funny thing is that even the AzureRM portal can't fully communicate with the keyvault, it finds it, but when accessing the secrets it shows a yellow ribbon at the top of the page and shows "an error has occurred" 

I see posts about this since 2015, I don't think it was ever resolved.

### Script/Steps for Reproduction
Create a Keyvault and immediately create Secrets in it.
You can also try to make a loop function that will ping this keyvault resource hostname, the time it takes to receive a response will be different each execution

**Comment by maddieclayton** [comment]
@RandalliLama Can you check out this issue?

**Comment by pixelicous** [comment]
#1524 referenced this issue from 2015, still open. I'll appreciate a response.

**Comment by SumedhBarde-MSFT** [comment]
@pixelicous - the replication time for Azure DNS varies. The vast majority should complete within 15s. Are you finding two minutes insufficient quite often?

Currently New-AzureRMKeyVault returns right away. We are looking at ways we can make it more intuitive that this operation takes time (without breaking existing callers). But the more important question is the one I ask above to ensure the delay you are seeing is within expected limits.

**Comment by pixelicous** [comment]
@SumedhBarde-MSFT It happens quite often.. The probldm isnt how the cmdlet responds but the API becuaee terraforma also has the same problems and it uses the API.. So that has to change at the root.. Not at the cmdlet level.
On some clients it happens constantly.. I deployed a VM and configed my automation environment there, every execution fails to get the secrets.. As i wrote above even the portal has a ribbon that shows an error communicqting with the keyvault.

If Microsoft can provide some sort of diagnosis tool to trace and log i can execute it while it fails.. It might give extra insight. It seems like this issue is open for a very long time without resolution

**Comment by pixelicous** [comment]
@SumedhBarde-MSFT Below reference to the timeout increase in terraform code:
https://github.com/terraform-providers/terraform-provider-azurerm/commit/d9772b1accd4007488bfc393eedf7c36d6641c78

This doesn't solve the problem. The API shouldn't return the object

**Comment by RandalliLama** [comment]
@pixelicous The code change you reference doesn't address the problem at all.  That code will still check for the dns name immediately.  The change will cause it to wait longer for the second check, but that doesn't help.  The code needs to be changed to wait for at least 15 seconds between creating the vault and the very first time DNS is queried.

**Comment by pixelicous** [comment]
@RandalliLama That is what i referred to, that the second check also doesnt work. The problem shouldn't be solved on the third party tools side though. I opened a ticked with microsoft anyhow. Thanks!

**Comment by SvetlanaPan** [comment]
Any progress on this issue?
Still faced with the same behavior

**Comment by RandalliLama** [comment]
There is a fix in the latest preview version of the .NET SDK which will GA no earlier than July.  The latest Azure PowerShell cmdlets have the fix.  The Azure GoLang SDK does not yet have the fix and won't get it until at least July.  Once the Azure GoLang SDK is updated, Terraform would then need to take a dependency on the newer SDK.  

@schaabs fyi

**Comment by pixelicous** [comment]
@RandalliLama Actually terraform has solved this issue with their previous azurerm provider version, the new change might break things on terraform's end.

Please revisit this issue and update once this problem is fixed on Microsoft's side.. can't understand how come a resource has such a fundamental flow for so long without a quicker fix.

Thanks for your time and response, appreciated.

**Comment by RandalliLama** [comment]
@pixelicous I will be sure to followup on this issue when the fix is GA'ed.

I would be surprised if the change breaks Terraform.  Current clients return success as soon as the Key Vault service acknowledges that it has received the request.  The fix causes the synchronous forms of the vault creation API to wait until Key Vault acknowledges not just that it has received the request, but that the vault has actually been created.  The Key Vault service waits a hard coded amount of time to ensure that DNS has had time to propagate before indicating successful vault creation.  If a better method of ensuring the DNS entry is available for clients is implemented in the future, it will be simple to update the logic in the Key Vault service and clients will get the improved behavior for free.  At worst Terraform will see vault creation latency increase.

**Comment by pixelicous** [comment]
@RandalliLama Hey, yes i thought about it afterwards, it shouldn't break, worst comes to worst it would be latency increase. Thanks for the update.

**Comment by placidseven** [comment]
Is this still an issue? @maddieclayton linked the issue to https://github.com/Azure/azure-powershell/issues/1524 and closed the other one out. I don't see any activity here for over a year and still we are getting DNS request errors.

**Comment by diepes** [comment]
I just ran into this creating a vault manually and not seeing the dns for 15minutes.
Is caching on dns servers causing this to be even worse ?

Could this be exacerbated by microsoft dns setup ?
returning SOA with 6000s timeout , 100minutes !!!

From https://rule11.tech/the-dns-negative-cache/
". If server not found is the response, then negative cache timeout is locally configured. If an NXDOMAIN record is returned, the negative cache is set to timeout based on the timeout found in the SOA."

# dig xxx.vault.azure.net
;; QUESTION SECTION:
;xxx.vault.azure.net.	IN	A

;; AUTHORITY SECTION:
vault.azure.net.	**5709**	IN	SOA	prd1.azuredns-cloud.net. msnhst.microsoft.com. 10001 900 300 604800 60

**Comment by pixelicous** [comment]
I can't believe this issue is this open, didn't even notice it. Luckily for me I stopped working with the dreadful Azure.. Closing this issue
