### ISSUE TITLE
Set-AzureRmRoleDefinition cmdlet documentation example references the wrong cmdlet

### ISSUE THREAD

**Issue by rkyttle** [Azure/azure-powershell#5464]
### Script/Steps for Reproduction
Visit https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/set-azurermroledefinition?view=azurermps-5.1.1

Under Examples, the example "Update using PSRoleDefinitionObject" is calling New-AzureRmRoleDefinition on its last line.

Shouldn't this example be using Set-AzureRmRoleDefinition instead?

**Comment by markcowl** [comment]
Hi @rkyttle We will take a look.  Meanwhile, did you know that you can click the 'edit' link on that page and  edit the document yourself?

**Comment by maddieclayton** [comment]
This is actually fixed in the latest documentation (you were looking at 5.1.1 and it is updated in 5.2.0): https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/set-azurermroledefinition?view=azurermps-5.2.0

Closing as fixed.

**Comment by rkyttle** [comment]
Thanks Mark!  I am aware of the edit option, I just hadn't used this cmdlet before so I wasn't sure if I had things right :)

Thanks Maddie!  I see the update, I was just going from a link that Bing brought me to, and I didn't notice that I wasn't looking at the latest docs.

**Comment by rkyttle** [comment]
Thinking more on this, even though the latest version of the docs has been updated, shouldn't we still correct this documentation on the version 5.1.1 site?  While I believe its always best to use the latest and greatest, when you do a Bing search for this cmdlet it brings you to the 5.1.1 docs.  I feel this should still get updated, and I am happy to fork and do a pull request if you prefer.
