### ISSUE TITLE
Storage account: xxxxxxxxx not found. Selected Connection 'ServicePrincipal' supports storage account of Azure Resource Manager type only. 

### ISSUE THREAD

**Issue by rokmicrosoft** [Azure/azure-powershell#6202]
Customer is getting this issue Storage account: xxxxxxxxx not found. Selected Connection 'ServicePrincipal' supports storage account of Azure Resource Manager type only. 
It happened after installing the updated version of Azure RM. After uninstall it started working fine.
Version -  PowerShell 6.0
Can you please look into it?

**Comment by sepharg** [comment]
Started happening on an "Azure File Copy" TFS task to me as well

**Comment by blueww** [comment]
@rokmicrosoft  @sepharg 

I tried to repro the issue with Azure Powershell 6.0.0 (AzureRm.Storage Version 5.0.0), and the latest Azure RM.storage 5.0.1, But both not reproed. The Start-AzureStorageFileCopy work fine on my machine.

Could you give more detail for how  to repro the issue (hide credential if any)?
1. Run "Get-module" after the issue repro, and give the result. We need the module version in the result to investigate the issue.
2. Give a PowerShell script which can repro the issue on your machine. This can help us to repro the issue.
3. Run the problem cmdlets with -debug parameter, and give the result. It can give us more clu on how the issue happen.
4. Just after the issue happen, run "$error[0].Exception.ToString()", and give the result.  It can also give us more clu on how the issue happen.

**Comment by sepharg** [comment]
Sure, here's the log I get from TFS (stripped out of credentials)

2018-05-11T13:35:56.5068549Z Executing the powershell script: C:\Install\agent-03\tasks\AzureFileCopy\1.0.42\AzureFileCopy.ps1 
2018-05-11T13:35:56.8349887Z Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1 
2018-05-11T13:35:58.2568820Z AzurePSCmdletsVersion= 1.3.2 
2018-05-11T13:35:58.3350104Z Get-ServiceEndpoint -Name 4e3b17e6-5635-4428-a8fd-51b58631fc32 -Context Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.TaskContext 
2018-05-11T13:35:58.3818816Z tenantId= ******** 
2018-05-11T13:35:58.3818816Z azureSubscriptionId= *** 
2018-05-11T13:35:58.3818816Z azureSubscriptionName= **** Development 
2018-05-11T13:35:58.5850139Z Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential 
2018-05-11T13:35:59.9287734Z Select-AzureRMSubscription -SubscriptionId *** -tenantId ******** 
2018-05-11T13:36:00.5069103Z ##[debug]Starting Azure File Copy Task 
2018-05-11T13:36:00.5069103Z ##[debug]connectedServiceNameSelector = ConnectedServiceNameARM 
2018-05-11T13:36:00.5225430Z ##[debug]connectedServiceName =  
2018-05-11T13:36:00.5225430Z ##[debug]connectedServiceNameARM = 4e3b17e6-5635-4428-a8fd-51b58631fc32 
2018-05-11T13:36:00.5225430Z ##[debug]sourcePath = C:\Install\agent-03\_work\a70c1c28c\PageRank.release\PagerankProcessorFiles\ci 
2018-05-11T13:36:00.5225430Z ##[debug]storageAccount =  
2018-05-11T13:36:00.5225430Z ##[debug]storageAccountRM = nessieactivitiesci 
2018-05-11T13:36:00.5225430Z ##[debug]destination type = AzureBlob 
2018-05-11T13:36:00.5225430Z ##[debug]containerName = customactivitycontainerv2 
2018-05-11T13:36:00.5225430Z ##[debug]blobPrefix = pagerankjobprocessor 
2018-05-11T13:36:00.5225430Z ##[debug]environmentName =  
2018-05-11T13:36:00.5225430Z ##[debug]environmentNameRM =  
2018-05-11T13:36:00.5225430Z ##[debug]resourceFilteringMethod = machineNames 
2018-05-11T13:36:00.5225430Z ##[debug]machineNames =  
2018-05-11T13:36:00.5225430Z ##[debug]vmsAdminUserName =  
2018-05-11T13:36:00.5225430Z ##[debug]targetPath =  
2018-05-11T13:36:00.5225430Z ##[debug]additionalArguments =  
2018-05-11T13:36:00.5225430Z ##[debug]cleanTargetBeforeCopy = false 
2018-05-11T13:36:00.5225430Z ##[debug]copyFilesInParallel = true 
2018-05-11T13:36:00.5225430Z ##[debug]skipCACheck = true 
2018-05-11T13:36:00.5225430Z ##[debug]enableCopyPrerequisites = false 
2018-05-11T13:36:00.6475376Z ##[debug]Installed Azure PowerShell version: 1.3.2 
2018-05-11T13:36:00.6475376Z ##[debug]Required AzureUtility: AzureUtilityGTE1.0.ps1 
2018-05-11T13:36:00.6475376Z ##[debug]Loading AzureUtilityGTE1.0.ps1 
2018-05-11T13:36:00.6631652Z ##[debug]Connection type used is ServicePrincipal 
2018-05-11T13:36:00.6787858Z ##[debug]Validating minimum required azure powershell version is greater than or equal to 0.9.0 
2018-05-11T13:36:00.6787858Z ##[debug]Installed Azure PowerShell version: 1.3.2 
2018-05-11T13:36:00.6787858Z ##[debug]Validated the required azure powershell version is greater than or equal to 0.9.0 
2018-05-11T13:36:00.6944106Z ##[debug][Azure Call]Getting resource details for azure storage account resource: nessieactivitiesci with resource type: Microsoft.Storage/storageAccounts 
2018-05-11T13:36:01.7256830Z ##[debug][Azure Call]Retrieved resource details successfully for azure storage account resource: nessieactivitiesci with resource type: Microsoft.Storage/storageAccounts 
2018-05-11T13:36:01.7569233Z ##[debug](ARM)Storage account: nessieactivitiesci not found 
2018-05-11T13:36:01.8038119Z ##[error]Storage account: nessieactivitiesci not found. Selected Connection 'ServicePrincipal' supports storage account of Azure Resource Manager type only. 


The task we're referring to is the following:

![image](https://user-images.githubusercontent.com/3963438/39982254-04ec36de-5754-11e8-9e7d-d7dd6374ca10.png)

**Comment by blueww** [comment]
@markcowl , @cormacpayne 

It seems the issue does not come from storage cmdlets, but from Get-AzureRmResource.


https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureFileCopy/AzureUtilityGTE1.0.ps1#L27

I see this line of code filter account with "ResourceName" But actually the output of the cmdlet has property "Name", but not property "ResourceName"

**Comment by rokmicrosoft** [comment]
@blueww  Thanks ..In azure powershell version 6.0 in Get-AzureRmResource ResourceName is not supported this is the reason our task is failing. We will update this in our task.

**Comment by markcowl** [comment]
Sounds like this is resolved, closing

**Comment by pshahid786** [comment]
@rokmicrosoft  do you know how are we going t this fixed and anyway to get us informed if its fixed? is there any alternative that we can use until this is fixed?

**Comment by rokmicrosoft** [comment]
@pshahid786  Please downgrade AzureRm version to 5.7.0 . If you still face any issue feel free to ping us.

**Comment by rokmicrosoft** [comment]
We had already identified the issue.
We will hotfix this task Till then you can downgrade your AzureRm module to 5.7.0 it should work.
If you still face any issue feel free to contact us.

**Comment by sepharg** [comment]
Many thanks @rokmicrosoft ! do you have an approx ETA on the hotfix?

**Comment by rokmicrosoft** [comment]
@sepharg  This error usually happened when importing multiple versions of AzureRM.Profile. 
[Stack-overflow solution link](https://stackoverflow.microsoft.com/questions/96243/use-management-group-commandlet-in-vsts-azure-powershell-task-the-typeconverte/96245#96245 ).

**Comment by sepharg** [comment]
@rokmicrosoft that's a private (enterprise) stackoverflow link, can't access it :(

**Comment by rokmicrosoft** [comment]
@sepharg  

Error:-
VERBOSE: Module 'AzureRM.ManagementGroups' was installed successfully to path 
VERBOSE: 'C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\AzureRM.ManagementGroups\0.0.1'.

The following error occurred while loading the extended type data file:
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": 
The TypeConverter was ignored because it already occurs.

Script :- 
if (Get-Module -ListAvailable -Name AzureRM.ManagementGroups) {
   Write-Host "Module exists"
} else {
  Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
  Install-Module -Name AzureRM.ManagementGroups -Force -Verbose -Scope CurrentUser -AllowPrerelease
}
Import-Module AzureRM.ManagementGroups -Force

Solution :- Reason :- Error in Typedata when importing multiple versions of AzureRM.Profile 
AzureRM.profile\4.5.0 is imported due to Azure.RM (5.1.1) installation and when you are trying to install AzureRM.ManagementGroups it again install AzureRM.profile\4.6.0.


Solution :- The typedata is automatically added on import, if it already exists this error is thrown. If you remove the module, before importing the later version, this does not occur.


Remove-Module -Name AzureRM.Profile -Force 
if (Get-Module -ListAvailable -Name AzureRM.ManagementGroups)
{ 
Write-Host "Module exists" 
}
else 
{ 
Install-PackageProvider -Name NuGet -Force -Scope CurrentUser 
Install-Module -Name AzureRM.ManagementGroups -Verbose -Force -Scope CurrentUser -AllowPrerelease 
}

Worked after added "Remove-Module -Name AzureRM.Profile -Force" before my script.

**Comment by sepharg** [comment]
Thing is, I'm not importing anything myself, it's all done by the TFS task 

C:\Install\agent-03\tasks\AzureFileCopy\1.0.42\AzureFileCopy.ps1

Are you suggesting I edit this manually?

**Comment by blade-feng-wang** [comment]
it's a very critical bug for us. we're using the ADF2.0 powershell, I updated the powershell version from 4.x to 5.x. But after that, the file copy task doesn't work. If I uninstall the version 5, the ADF2.0 API will not work, can you please fix this bug ASAP.

**Comment by rdtechie** [comment]
When will the hotfix for this be implemented? Any ETA?

**Comment by aameersulthan** [comment]
In tfs build using "Hosted VS2017" trying  "Azure Blob File copy" task to move the artifact static content to Blob storage. Ended with this issue. Tried "Azure Blob File copy" 1.0 and "2.0(Preview). Couldn't proceed further any help? cc @rokmicrosoft  @sepharg

**Comment by qJake** [comment]
Likewise, we are trying to use the Azure File Copy TFS release task with TFS 2018 U2 and are receiving the same error, preventing us from deploying to our Azure VMs using TFS Releases.

When will a fix be available for this?

Can anyone provide the correct PowerShell command(s) to run in order to downgrade the PowerShell environment on the build agent to 5.7.0 in the meantime?

**Comment by mkusmiy** [comment]
After upgrading AzureRM from v5.7.0 to v6.8.1 we ran into this very problem with Azure File copy task in our TFS. Issue can be fixing by merging following line in the very same file from v2 of the task:
$azureStorageAccountResourceDetails = (Get-AzureRMResource -ErrorAction Stop) | Where-Object { ($_.ResourceType -eq $ARMStorageAccountResourceType) -and ($_.Name -eq $storageAccountName)}
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureFileCopyV2/AzureUtilityGTE1.0.ps1

**Comment by sepharg** [comment]
thanks @mkusmiy 
We recently updated to TFS 2018 and I've also had to apply your change, since azure file copy started to fail once again
It'd be great if someone from Microsoft can acknowledge this issue and create a permanent fix, because the error keeps coming back to haunt us

**Comment by sepharg** [comment]
> Sounds like this is resolved, closing

it's not really resolved

**Comment by feynman11** [comment]
We are having the same issue ##[error]Storage account: XXXXXXX not found.

**Comment by pshahid786** [comment]
Hi,
If you have vats build agent installed in your own server than u have to update azure powercli, and also update vsts agent. Once its all updated, restart your agent and server. Make sure you are using latest version in you azcopy, and azure download vsts build tasks.  This should resolve the issue.

Shahid Patel

**Comment by soccerjoshj07** [comment]
Also having the issue when upgrading AzureRM to 6.11.0 coming from 5.7.0. Reverting back to 5.7.0 is not feasible because then we cannot take advantage of 6.11.0 features. Do we really need one server for 5.7.0 deploys and one server for 6.11.0 deploys? 

See my comment here for task hotfix that worked for me. https://github.com/Microsoft/azure-pipelines-tasks/issues/1660#issuecomment-434824826

**Comment by ActualReverend** [comment]
I may have had a different cause, but with the same error you had, I was able to fix it by installing https://github.com/Azure/azure-powershell/releases/tag/v1.0.2-December2015  on my build servers.  I had AzureRM 6.13 and was still getting the error.  (I found that link at the page:  https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureFileCopyV2 )

**Comment by feynman11** [comment]
@ActualReverend thanks for the suggestion. Installing that version also resolved the issue for us.

**Comment by jlienSage** [comment]
I was struggling with this issue and discovered the cause was that TFS 2018 pipeline tasks must use Powershell 5.7.0. However, we had scripts we had written against Powershell 6.13.1 and some commands failed in a 5.7.0 environment. The solution for us since we obviously do not have the ability or desire to tamper with the internals of TFS 2018 was to rewrite our scripts against 5.7.0. Hopefully this is helpful to someone coming here with a similar problem.
