### ISSUE TITLE
New-AzureRMVM Object reference not set to an instance of an object - previously working script

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Azure/azure-powershell#6847]
Currently on 6.6.0

Had a script to create a new VM from a stored VHD (been using for ~8 months now).

I'm all of a sudden getting **New-AzureRmVM : Object reference not set to an instance of an object.**

Omitting the creation of RG, networking, etc. Below is the script to create OS disk and VM.

Has anything changed in the latest releases?

```
Write-Host "Creating OS Disk" -ForegroundColor Green
# OS Disk
New-AzureRmDisk -DiskName $osDiskName -Disk `
(New-AzureRmDiskConfig -AccountType Premium_LRS  `
        -Location $location -CreateOption Import `
        -StorageAccountId $storageAccountId `
        -SourceUri $osVHDUri) `
    -ResourceGroupName $resourceGroupName
$osDisk = Get-AzureRMDisk -DiskName $osDiskName -ResourceGroupName $resourceGroupName

Write-Host "Setting VM Configuration" -ForegroundColor Green
#Initialize virtual machine configuration
$VirtualMachine = New-AzureRmVMConfig -VMName $virtualMachineName -VMSize $virtualMachineSize
$VirtualMachine = Set-AzureRmVMOSDisk -VM $VirtualMachine -ManagedDiskId $osDisk.Id -CreateOption Attach -Windows
$VirtualMachine = Add-AzureRmVMNetworkInterface -VM $VirtualMachine -Id $nic.Id

#Create the virtual machine with Managed Disk
Write-Host "Creating Virtual Machine" -ForegroundColor Green
New-AzureRmVM -VM $VirtualMachine -ResourceGroupName $resourceGroupName -Location $location -Verbose

Write-Host "Enabling Auto-Shutdown" -ForegroundColor Green
Enable-AzureRMVmAutoShutdown -SubscriptionId $subscriptionId -ResourceGroupName $resourceGroupName -VirtualMachineName $virtualMachineName -TimeZone $timeZone


### Debug output

``` DEBUG: AzureQoSEvent: CommandName - New-AzureRmVM; IsSuccess - False; Duration - 00:01:15.8115447; Exception - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Management.Compute.Models.StorageAccountTypes.ToString()
   at Microsoft.Azure.Management.Compute.Models.StorageAccountTypesConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty
containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty
containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty
containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty
containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty
containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.SerializeObject(Object obj, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.<DefaultExecuteCmdlet>b__114_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.DefaultExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord(); ```

**Comment by markcowl** [comment]
@jeanfrancoislarente Thanks for the report, cna you also provide the output when executing ```Resolve-AzureRmError -Last``` immdeiately after the error?

@singhkays @hyonholee can you take a look?

**Comment by JVSemmelrock** [comment]
Issue with error "Object reference not set to an instance of an object." also applies to Get-AzureRmVm.  I had a prior working script suddenly start failing after 6.6.0 update and after discovering that the example powershell at https://docs.microsoft.com/en-us/azure/virtual-machines/windows/attach-disk-ps also now fails with the same error i rolled back to an earlier module and it succeeded.

The only time Update-AzureRmVm would acccept the vm object on 6.6.0 was via a pipestream, but, at least in the adding-a-data-disk flow, something still wasn't actually functioning.

**Comment by jeanfrancoislarente** [comment]
@singhkays @hyonholee @markcowl 

Here is the error for New-AzureRMVm

```HistoryId: 200


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Management.Compute.Models.StorageAccountTypes.ToString()
                    at Microsoft.Azure.Management.Compute.Models.StorageAccountTypesConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract
                 collectionContract, JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract,
                 JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract,
                 JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract,
                 JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
                    at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
                    at Microsoft.Rest.Serialization.TransformationJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract
                 collectionContract, JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
                    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.SerializeObject(Object obj, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__24.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.<DefaultExecuteCmdlet>b__114_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.DefaultExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {New-AzureRmVM}
Line           : New-AzureRmVM -VM $VirtualMachine -ResourceGroupName $resourceGroupName -Location $location

Position       : At C:\Projects\gh.s.hh.utils\Azure\CreateVMFromVhd.ps1:176 char:1
                 + New-AzureRmVM -VM $VirtualMachine -ResourceGroupName $resourceGroupNa ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 200```

**Comment by jeanfrancoislarente** [comment]
Read another thread about storage account type names changing with/without the underscore. Since the disk is being created as **Premium**, is it possible that the New-AzureRMVm command, which is trying to create boot diagnostics in basic storage is using the wrong name for the "standard" storage account **type**?

**Comment by jeanfrancoislarente** [comment]
**Works correctly in 6.3.0**. Didn't try any newer versions except for the reproducible 6.6.0 version.

**Comment by OmegaMadLab** [comment]
Faced same issue yesterday on **5.4.0**. Solved by specifying StorageAccountType in the Set-AzureRmVMOSDisk phase, before creating the VM with New-AzureRmVm:
`#Attach OS disk
$TestVm = Set-AzureRmVMOSDisk -VM $TestVm -ManagedDiskId $Disk.Id -CreateOption Attach -Windows -StorageAccountType Premium_LRS`

Previously I was specifying storage sku only in New-AzureRmDiskConfig, as per official documentation, and New-AzureRMVm stopped working after last update.

**Comment by jeanfrancoislarente** [comment]
Fantastic @OmegaMadLab - re-installed 6.6.0 and tried by adding the StorageAccountType to the Set-AzureRmVMOSDisk CmdLet and it worked like a charm.

Interesting that it works in 6.3.0 without setting that value but not in 5.4.0 and 6.6.0

**Comment by hyonholee** [comment]
The root cause is the generated client library has a converter for storage account type, and even the value is null, it tries to write the value by calling value.ToString() (below line).
https://github.com/Azure/azure-sdk-for-net/blob/8852cf540d6b68acf2ce7f0d3505749c8dd9aa91/src/SDKs/Compute/Management.Compute/Generated/Models/StorageAccountTypesConverter.cs#L49

**Comment by Karishma-Tiwari-MSFT** [comment]
@hyonholee @singhkays  Is there an update on this issue? Many customers are still facing the same issue. Is there a timeline on when this be fixed? Thanks.

**Comment by BrandonBoone** [comment]
FYI: @OmegaMadLab 's fix is also working when calling `Add-AzureRmVMDataDisk`

```
$vmConfig = Add-AzureRmVMDataDisk -VM $vmConfig -VM $vmConfig -StorageAccountType Premium_LRS #...
```

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
