### ISSUE TITLE
ARM Resource [Group] Tags :: Usability Problem

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#726]
When you configure a resource tag, you have to specify a PowerShell `HashTable` with two keys (elements):

- Name
- Value

Since an ARM Resource Tag is simply a key-value pair, just like a single-key `HashTable`, I shouldn't have to specify **two** `HashTable` keys to declare a Resource Tag.

This is what it **should** look like:

```powershell
@{
    Tag1 = 'Tag1Value';
    Tag2 = 'Tag2Value';
}
```

![image](https://cloud.githubusercontent.com/assets/466713/9204339/e507a62c-4019-11e5-9e58-7a9d13cb5a03.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by bmoore-msft** [comment]
Actually our implementation seems of resource tags seems odd on both get and set.  A "get" of a single tag (created by json) returns to entries in the hashtable one for name and one for value.  This means the normal parsing your might do on a hashtable doesn't work, you have to understand our special implementation.

For example:
PS C:\Windows\System32\WindowsPowerShell\v1.0> (get-AzureResource -ResourceType Microsoft.Storage/storageAccounts -ResourceName sa -ResourceGroupName aStore -OutputObjectFormat New).tags

Name                           Value                                                                                                                                                                  
----                           -----                                                                                                                                                                  
Value                          sa                                                                                                                                                                     
Name                           displayName                                                                                                                                                            

That should actually return:

Name                        Value                                                                                                                                                                  
----                             -----                                                                                                                                                                  
displayName              sa

**Comment by markcowl** [comment]
@pcgeek86 The issue is, a tag is not simply a key/value pair.  A tag may be either a Key only or a key valur pair

as in

'Accounting'

or 
'Department' = 'Accouting'

and the provided OM is actually close to the rest API.

Agreed that we should provide a better user experience, jsut allowing a dictionary / hash table for a set of tags.

**Comment by bmoore-msft** [comment]
The problem with the OM is that we say return a System.HashTable, but can't do typical operations on it like Add.  I tried updating/appending to the tags on a RG and couldn't figure it out.  I should be able to do something like:

    $t = (Get-AzureResourceGroup MyGroup).tags
    $t.Add("foo", "bar")
    $t.Add(Name="foo",Value="bar")
    $t.Add("bar")

None of that works.  I *can* set/replace the tags (in some cases), but I cannot append/update them.

**Comment by pcgeek86** [comment]
@markcowl What's wrong with this? /cc @bmoore-msft 

```powershell
### Key only
@{ Accounting = $null; }

### Key and value
@{ Department = 'Accounting'; }
```

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
Tags are definitely hard to use in the current implementation. And updating them is not possible. Lets explore potential solutions.

**Comment by pcgeek86** [comment]
@ravbhatnagar Thanks for acknowledging the ticket, for acknowledging the usability problem, and for your support in finding an agreeable solution!

I've proposed a solution already. What's wrong with my proposal? Happy to have my proposal criticized, but let's talk about it directly, instead of talking around it. Help me understand why it would or wouldn't work.

**Comment by bmoore-msft** [comment]
I think Trevor's proposal makes sense - it works the same way as the platform does when using the REST API.  We seem to be headed toward consistency with the platform in the cmdlets, this would be another area where we could do that.

**Comment by ravbhatnagar** [comment]
@pcgeek86 - Your proposal definitely makes sense. The note I put was just for myself to discuss it with the team and get further feedback. Apologize if it caused any confusion.

**Comment by ravbhatnagar** [comment]
Could not get to this in the Apr release.

**Comment by pcgeek86** [comment]
@ravbhatnagar @bmoore-msft Will we see this in the May 2016 release?

**Comment by ravbhatnagar** [comment]
@pcgeek86 This is definitely one of the top items on the list for the May release.

**Comment by ravbhatnagar** [comment]
Folks - The current usability of tags in ARM PowerShell is not so great. We are planning to improve the experience around how you create a tag object, how its outputted and how it can be updated. I have consolidated the feedback from above. Please provide any feedback on the proposed design. Thanks for your help on this.

**Current Design:**
1. To specify a tag object, I have to do the following-
       @{
           Name = ‘TagName1’;
           Value = ‘TagValue1’;
           Name=’TagName2’;
           Value=’TagValue2’;
}
2. When I get the tags of a resource (for example), I get the following output:
PS C:\WINDOWS\system32> (Get-AzureRmResource -ResourceId /subscriptions/xxxx/resourceGroups/temprg5/providers/Microsoft.Insights/components/ravtestws13).Tags 
Name    Value                                                                                                                                        
----          -----                                                                                                                                        
Value      TagValue1                                                                                                                        
Name      TagName1                                                                                                                               
Value   TagValue2                                                                                                                                     
Name    TagName2
 3. Updating an existing tag or adding a new tag is difficult

**Proposed Design:**
 1. To specify a tag, I should do the following:
@{
     TagName1 = ‘TagValue1’;
     TagName2 = ‘TagValue2’;
}
Only specifying key for a tag should work by providing value as $null. Example - @{TagName1 = $null;}
2. Tags should be returned as follows- 
Name                    Value
TagName1          TagValue1
TagName2          TagValue2

3.Appending/Updating tags should work
$tags = (Get-AzureRmResourceGroup -Name ravdeleterg1).tags 
$tags.Add(‘tagName1’, ‘tagValue1’) 
Etc.

**Comment by bmoore-msft** [comment]
This looks right to me @pcgeek86 should add $0.02.  We should also make sure that the GET will return the same hash table passed in on the SET.  I think that's what you meant but code disambiguates everything :)

**Comment by pcgeek86** [comment]
The proposal matches my original proposal.

**Comment by ravbhatnagar** [comment]
@pcgeek86 - Do I take that as a yes :).
Another thing I would like to point out is that the below will still work -
@{Name='tagName1'; value='tagValue1'} as its still a valid key value pair.
 I guess we will have to give good examples in PS help and update our other documentation to point out how to use tags.

**Comment by pcgeek86** [comment]
@ravbhatnagar yes

**Comment by ravbhatnagar** [comment]
@pcgeek86 @bmoore-msft - Since this will be a breaking change and we don't want to catch any customer off guard, we will add a deprecation message this release and the actual change will ship in the next one. Its unfortunate since we have the PR ready with this change, but we have decided against it for this release.

**Comment by ravbhatnagar** [comment]
Moving this to June milestone.

**Comment by memark** [comment]
I'm not sure I understand the point of the warning I'm currently getting (which brought me here). Even if I have the time now to fix it, there is nothing I can do? I still have to wait for the new API? And when it arrives, what will happen, will I get an error?

**Comment by ravbhatnagar** [comment]
@memark -   The intent of adding the warning is to raise awareness about an upcoming breaking change. Seeing it the customers would know that such a change is coming in future and they might have to update the scripts. They can plan to move to the version containing the breaking change accordingly. 
When you start using the release which contains this change, your existing scripts using Tags might break and you will see an error.

Yes, the information currently provided in the warning does not help in things like providing guidance around fixing the scripts etc. But we are planning to address/improve such things in future (if we need to make such breaking changes again).

Any feedback on this front is welcome.

**Comment by ravbhatnagar** [comment]
Since this turned out to be a change impacting a lot of cmdlets from different teams, we are pushing this out by a month. The reason is to fix this across the board for all Azure cmdlets and give some warning about the upcoming change to customers of all those different cmdlets. The warning we added in added the last release was only to a subset of these cmdlets. 

So in the June release, all the cmdlets using this param will show this warning and then we will actually change it in the July release.

**Comment by jamesweb-ms** [comment]
Instead of a breaking change, how about providing new functionality while marking existing functionality as deprecated?  That way there is no rush to fix when a new version comes out but those that see the message can take immediate action (update scripts).

**Comment by iricigor** [comment]
@ravbhatnagar  If there will be more delays, would it possible to drop warning **only** if Tags are used in command and not each time I run the command?

**Comment by ravbhatnagar** [comment]
@iricigor - This is slated to go in the August release of Azure PowerShell which will be released in the first week of August. Concerns?

**Comment by jamesweb-ms** [comment]
@ravbhatnagar  is that going to be a Major release change (aka breaking) or minor with backwards compatibility?

**Comment by ravbhatnagar** [comment]
@jamesweb-ms - That will be a major release change.

**Comment by jaxoft** [comment]
You can do 
- read the tags from the VOP.
- Add or remove a tag from the array
- Update the VM tags

Example:
#$VM is your VM
$system=Get-AzureRmVm|?{$_.Name -eq $VM} 
$tags=$system.tags

        foreach ($VMtag in $tags.GetEnumerator()) 
        { 
            Write-Host "$($VMtag.Key) = $($VMtag.Value) "
            $TagsNew += @{name="$($VMtag.Key)" ; value="$($VMtag.Value)"} 

        }

( for example add new tag here...)
$TagsNew += @{name="$($VMtag.Key)" ; value="$($VMtag.Value)"} 


$system|Update-AzureRmVM -Tags @($TagsNew)

**Comment by ravbhatnagar** [comment]
Fixed in Aug release

**Comment by bourgeoisrebel** [comment]
The documentation for tags doesn't reflect this change, or the fact syntax is different between versions. 

https://azure.microsoft.com/en-gb/documentation/articles/resource-group-using-tags/

Although there was a warning included in the previous release, with a link leading to this page, after making the change, the command simply fails with no information about how to fix it. Even though there was a warning in the previous release, making these changes before the change caused the script to fail.  After the release, the only way i could find my way back to this page was to rollback the update to get the original warning again! 

Searching the web leads to the official documentation, which is wrong for any customer with the latest version of the Powershell module. If you have not seen previous warnings, and have just created a new VM for instance, with the latest powershell installed, you will see an error with no info on how to resolve it. Different machines with different versions will have different experiences. This can get very messy.

I appreciate this is a challenge, and a difficult balance to strike in an agile world, people rely on this stuff in productionised environments. You need to find a way to communicate this information, and write meaningful error messages for new or changed commands that can lead you to meaningful resolution, rather than lead you to the information before it is useful and revoke it afterwards.

I did eventually find the following releases page, which helps, but you have to know precisely what you are looking for and why. If you didn't already know there was a breaking change for tags, the significance would not stand out, and it's not associated to any error messages. https://github.com/Azure/azure-powershell/releases   

Although frustrated, I'm just hoping to provide useful feedback!

**Comment by ravbhatnagar** [comment]
@bourgeoisrebel - Thanks for the feedback and I understand your concern. We are constantly trying to improve our processes around breaking changes and how we help customers when such a change happens. Something we started doing this release, and will keep improving on, can be found here - https://github.com/Azure/azure-powershell/blob/dev/documentation/release-notes/migration-guide.2.0.0.md

Yes, we should have done a better job at aligning the doc changes with the release so that discoverability is not an issue. Hope to get better at this. @tfitzmac to address the doc issue.

Please keep the feedback coming.

**Comment by tfitzmac** [comment]
@bourgeoisrebel - thanks for this feedback. I have an update for the tags topic on Azure.com that should get published this afternoon. Currently, the PowerShell reference on MSDN typically lags the latest release by some days because there is a bit of work to get it ready.

**Comment by itaysk** [comment]
@tfitzmac @ravbhatnagar The docs are still wrong:
https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.resources/v3.4.0/set-azurermresourcegroup

**Comment by itaysk** [comment]
I would also like to add that the tags property in `Find-AzureRmResourceGroup` is a PSCustomObject, and the tags property in  `Get-AzureRmResourceGroup` is a HashTable. I think we should pick one. I would vote for Hashtable because it is easier to manipulate.

**Comment by prara06** [comment]
I am trying run Microsoft provided script to inherit and update tags from azure resource groups to resources.. The script will inherit add new tags and values but if resource already has tag then it will ignore and dont update the value.   Can you please advice what needs to be done to update tag and value inheritance.

# Get the resource group
$group = Get-AzureRmResourceGroup myResourceGroup

if ($group.Tags -ne $null) {
    # Get the resources in the resource group
    $resources = Get-AzureRmResource -ResourceGroupName $group.ResourceGroupName

    # Loop through each resource
    foreach ($r in $resources)
    {
        # Get the tags for this resource
        $resourcetags = (Get-AzureRmResource -ResourceId $r.ResourceId).Tags

        # If the resource has existing tags, add new ones
        if ($resourcetags)
        {
            foreach ($key in $group.Tags.Keys)
            {
                if (-not($resourcetags.ContainsKey($key)))
                {
                    $resourcetags.Add($key, $group.Tags[$key])
                }
            }

            # Reapply the updated tags to the resource 
            Set-AzureRmResource -Tag $resourcetags -ResourceId $r.ResourceId -Force
        }
        else
        {
            Set-AzureRmResource -Tag $group.Tags -ResourceId $r.ResourceId -Force
        }
    }
}
